### ISSUE TITLE
TModLoader Fatal error. Wont start up no matter what I do.

### ISSUE THREAD

**Issue by Acidcub** [bluemagic123/tModLoader#3455] opened 2023-05-06 13:23 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

tModLoader keeps Crashing. I played it this afternoon just fine, but when I came back and tried to launch it again, I got a crash. Vanilla Terraria works fine but whenever I boot up tModLoader I get this crash (see bellow for stacktrace) whenever the game tries to load or boot up it straight up crashes without even showing me the tittle screen.

I've tried the following fixes:

disabling all mods and resource packs by unsubscribing through the steam workshop 

Deleting the config.json and renaming it

Running as admin

Reinstall Terraria

Reinstall tModLoader

Reinstall both at the same time

Reinstall Xna Framework by downloading it from the Microsoft page

Delete Xna Framework and let Steam reinstall it

Disable all the mods (which is Calamity, the music pack and Magic Storage)

Any clue what I can do to fix it?

### Log File

System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerInternal(Camera camera, Player drawPlayer, Vector2 position, Single rotation, Vector2 rotationOrigin, Single shadow, Single alpha, Single scale, Boolean headOnly) in tModLoader\Terraria\Graphics\Renderers\LegacyPlayerRenderer.cs:line 221
   at Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer(Camera camera, Player drawPlayer, Vector2 position, Single rotation, Vector2 rotationOrigin, Single shadow, Single scale) in tModLoader\Terraria\Graphics\Renderers\LegacyPlayerRenderer.cs:line 118
   at Terraria.GameContent.UI.Elements.UICharacter.DrawSelf(SpriteBatch spriteBatch) in tModLoader\Terraria\GameContent\UI\Elements\UICharacter.cs:line 68
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 171
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 185
   at Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\GameContent\UI\Elements\UIList.cs:line 25
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 185
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 185
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 185
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 185
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 185
   at Terraria.GameContent.UI.States.UICharacterSelect.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\GameContent\UI\States\UICharacterSelect.cs:line 375
   at Terraria.UI.UserInterface.Draw(SpriteBatch spriteBatch, GameTime time) in tModLoader\Terraria\UI\UserInterface.cs:line 261
   at Terraria.Main.DrawMenu(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 39882
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49137
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48723
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
[09:20:23.119] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

### Actual Behavior

I opened my game and it goes into a black screen before crashing and showing an error log. i have no idea whats causing the problem and i have seen others with this issue in steam discussion forms.

### Additional Information

I opened my game and it goes into a black screen before crashing and showing an error log. I have no idea what's causing the problem and i have seen others with this issue in steam discussion forms. Please help I'm not experienced enough to find a solution.

**Comment by JavidPack** [comment] 2023-05-06 22:28
Please post the actual client.log file.

**Comment by JavidPack** [comment] 2023-05-06 22:43
Actually, duplicate of #3456, please post there.

**Closed as not planned by JavidPack** 2023-05-06 22:43 UTC
Labels: NEW ISSUE, Requestor-Player
