### ISSUE TITLE
Tmodloader crashes, unable to load into menu even WITHOUT any mods.

### ISSUE THREAD

**Issue by GalliusG** [bluemagic123/tModLoader#3456] opened 2023-05-06 16:05 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

2 weeks ago I started playing Tmodloader with my friends in the 1.4-stable version. Everything was fine until today that I was not able to get the game to load into main menu. The fatal error message (image provided) suggested that it was due to a mod's fault so I removed all the mods and still it's showing the same message. Since I wasn't able to load into menu to remove the mods, I had to remove them from steam workshop (image provided)[The mod folder in my Document is also empty as seen (images provided)]. Even then the game still says that it's due to a mod's fault for crashing. I have yet to seen any similar situation so I have no idea what to do. Please help.

The mods I was using in Tmodloader 1.4-stable were (image provided)
![image](https://user-images.githubusercontent.com/117636245/236634418-e07eaa7c-ba21-4f74-b26a-743e17a1a6db.png)
![image](https://user-images.githubusercontent.com/117636245/236634449-fc2d1d67-8a5a-4ef6-8bc6-08ddf4d2db54.png)
![image](https://user-images.githubusercontent.com/117636245/236634504-9ef3e255-cbd8-4b9e-9e9d-da3ca12d9031.png)
![image](https://user-images.githubusercontent.com/117636245/236634515-08454581-344e-4d94-9b68-883ba1ea2587.png)
![image](https://user-images.githubusercontent.com/117636245/236634551-5b264de9-f402-4bd7-8eec-996c59a30282.png)
![image](https://user-images.githubusercontent.com/117636245/236634641-c482379c-2bea-47f3-89af-f167bb0423d9.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11412736/client.log)

### Steps to reproduce

- Click "play" Tmodloader on steam
- Game crashes

### Reproduction frequency

Every time I try to open the game

### Additional Information

I can run my Terraria without any problem whatsoever but every time I try to launch Tmodloader it crashes before being able to  load into main menu.

**Comment by kmo12** [comment] 2023-05-06 20:38
Same crash. Got it when pressed Alt+F4 in multiplayer world.
For repair I tried (but it did't help):
Tried to do "clean install" both Terraria and tModLoader.
Tried to delete all cloud savings (with help of my friend on other PC).
Tried to delete savings folder both Terraria and tModLoader.
Tried to download game files from my friend's PC (also savings and configs)

Also cleaned all mods from Steam workshop and from local files.

Still see this crash, please help.

**Comment by TheMajorDucky** [comment] 2023-05-06 21:28
I had this same issue with my game but I was able to get it to work again.

Step 1 (atleast for how mine is working): Delete your C: drive (or whatever drive your terraria AND tmodloader) folders of the games.
2: Use steam to uninstall the game (Yes the files are gone but just do this for the reinstallation.)
3: Go to your documents and navigate your way to finding your terraria (and  I think there was a tmodloader folder too? If not then thats fine.) and then delete that. MAKE SURE YOU BACKUP YOUR CHARACTER OR WORLD BECAUSE THIS IS A HARD RESET!!!
4: Reinstall terraria and run it.
5: Close it and reinstall tmodloader/run that.
6: Hopefully it works!
Thank you.

**Comment by TheMajorDucky** [comment] 2023-05-06 21:28
> 

I posted a solution to this, hopefully it works for you.

**Comment by TheMajorDucky** [comment] 2023-05-06 21:33
It could be tmodloader itself having an issue. Even with the game opening, I click create character and it crashes with the same message. It looks like there was an update for tmodloader which is making it all crash. Other people in the steam discussion page report our issue too. I guess we have to wait for a fix on the update. Woohoo!

**Comment by Acidcub** [comment] 2023-05-06 21:43
Man i sure hope this can be fixed with a patch, i was in the middle of a calamity hardmode for the worthy run when the crash hit me like a semitruck.

**Comment by JavidPack** [comment] 2023-05-06 22:52
It seems a lot of people have this issue as of a few hours ago. My current thought is that some mod or resource pack recently updated and is corrupting the player saves due to a bug. tModLoader can't handle that corruption, so the game crashes, even though the mod is now disabled.

I'd like everyone who has been linked to this issue thread to post the files for the player that they last played (.plr and .tplr) prior to this bug. Those files will help me look into this issue.

The other thing I'd like is for people to post their mod lists as text, my guess is there is some mod in common that is the cause of this, so cross referencing everyone's mod lists will help.

If you have any resource packs from Terraria or tModLoader, please mention those as well.

Another thing someone experiencing this issue can do is try removing players from the Players folder and checking if the game still crashes on the players menu. If that works, then restoring from a backup might be the solution to playing tmod again. (https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#world-and-player-backups)

Another thing to note is 1.4 most likely won't update to fix a rare issue like this (We are working on 1.4.4 right now). I'm pretty sure this is caused by a mod, so once we identify it I can remove it from the workshop or get that mod fixed.  The players might not be recoverable. We can at least make sure it's fixed for 1.4.4 (You can also test loading the player on 1.4.4 if you want.)

**Comment by vicentsargues** [comment] 2023-05-06 23:11
I guess the problem is not a mod bc i delete whole folder and the problem persist

**Comment by Acidcub** [comment] 2023-05-06 23:35
> The other thing I'd like is for people to post their mod lists as text, my guess is there is some mod in common that is the cause of this, so cross referencing everyone's mod lists will help.

I would post the files of my characters but i cant seem to find the .plr nor the tplr files in the tModloader files nor the user files or document files.

**Comment by Slumey** [comment] 2023-05-06 23:54
So, the game will only launch if I have ZERO files in C:\Users\mrslu\Documents\My Games\Terraria\tModLoader\Players. After launching you have to MANUALLY make sure your mods are loaded. Then you can drag your player files back into the directory and play.

If you launch the game with a player in the directory it will be corrupted and you will no longer be able to use it. So you have to make a copy/save elsewhere before you close the game.

If you have steam's cloud sync on then there is a chance that steam is downloading those corrupted player files back and that could be the cause for why you can use the work around.

The circumstances prior to this are:

I had a resource pack enabled, I didn't like to look so I exited the multiplayer world to turn it off, after turning it off I go to join my friend and while I was loading into the world my game crashed. I reopened the game and started getting that error, when I went into my player files at first after seeing the "workaround" in the discord, the files for the player I was using for the playthrough were gone. Reinstalling does nothing, I am not using steam cloud sync at all, I had every mod unsubscribed from the workshop and that didn't help.

I had a mod-pack file on my pc since I was playing with friends and used that to redownload all of my mods. Currently I do not know if the game will work without having the same exact mods before this error. I am currently using the above workaround to play.

Please contact me on discord Slime#1000 for questions or if you want some more information.

My Mod List: (I know it's the ones that are only enabled but these are the only mods I have downloaded)
[ModList.txt](https://github.com/tModLoader/tModLoader/files/11413572/ModList.txt)

Corrupted Player:
[Corrupted Player Files.zip](https://github.com/tModLoader/tModLoader/files/11413574/Corrupted.Player.Files.zip)

Not Corrupted Player: 
[NOT Corrupted Player Files.zip](https://github.com/tModLoader/tModLoader/files/11413575/NOT.Corrupted.Player.Files.zip)

Resource Pack:
[CalamityTexturePack.zip](https://github.com/tModLoader/tModLoader/files/11413593/CalamityTexturePack.zip)

**Comment by aLIEz3Tears** [comment] 2023-05-07 00:15
I first came across this issue when doing Calamity's bossrush on a friend's world. The game wouldn't teleport us for the WoF Fight, so we went to both restart out game. Afterwards I got the error message. I tried reinstalling, deleting all mods, verifying file integrity and changing the version. Nothing worked. Deleting my player files let's me start the game and drag them back into the \player directory. 

Corrupted Player Files: 
[corruptedrchars.zip](https://github.com/tModLoader/tModLoader/files/11413615/corruptedrchars.zip)

(Edit: Another character that I created after originally encountering the bug is also causing the game to crash and I cannot access character creation when there are player files in the \players directory)

modlist:
[modlist.txt](https://github.com/tModLoader/tModLoader/files/11413616/modlist.txt)

**Comment by sebap2004** [comment] 2023-05-07 00:33
My game for some reason crashes but like 1/100 times it decides to load and then breaks. My issue started when i Alt-f4'd a session because i was frozen when i tried to open a chest

**Comment by Solxanich** [comment] 2023-05-07 03:58
Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week.
Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.

If you are still having this issue, give that a shot. 
If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.

**Comment by GalliusG** [comment] 2023-05-07 04:39
> Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> 
> If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.

This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).

By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.

I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.

Thank you.

Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.

=> Opt out of steam Beta -> Verify game file integrity -> game should run as intended.

**Comment by Acidcub** [comment] 2023-05-07 05:24
> > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> 
> This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> 
> By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> 
> I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> 
> Thank you.
> 
> Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> 
> => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.

OMG this actually worked. Thank you so much friend. I went from trying out the beta to going to old steam client and it immediatly fixed it.

**Comment by Nine-Month** [comment] 2023-05-07 14:54
> > > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> > 
> > 
> > This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> > By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> > I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> > Thank you.
> > Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> > => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.
> 
> OMG this actually worked. Thank you so much friend. I went from trying out the beta to going to old steam client and it immediatly fixed it.

me too

**Comment by KalebGarrett** [comment] 2023-05-07 19:50
Step 1 (atleast for how mine is working): Delete your C: drive (or whatever drive your terraria AND tmodloader) folders of the games. 
2: Use steam to uninstall the game (Yes the files are gone but just do this for the reinstallation.) 
3: Go to your documents and navigate your way to finding your terraria (and I think there was a tmodloader folder too? If not then thats fine.) and then delete that. MAKE SURE YOU BACKUP YOUR CHARACTER OR WORLD BECAUSE THIS IS A HARD RESET!!! 
4: Reinstall terraria and run it. 
5: Close it and reinstall tmodloader/run that. 
6: Hopefully it works! Thank you.

This worked or me! :)

**Comment by Slumey** [comment] 2023-05-07 22:31
> > > > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > > > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> > > 
> > > 
> > > This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> > > By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> > > I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> > > Thank you.
> > > Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> > > => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.
> > 
> > 
> > OMG this actually worked. Thank you so much friend. I went from trying out the beta to going to old steam client and it immediatly fixed it.
> 
> me too

This also worked for me.

**Comment by WhineyWaffles** [comment] 2023-05-08 08:10
> > > > > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > > > > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> > > > 
> > > > 
> > > > This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> > > > By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> > > > I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> > > > Thank you.
> > > > Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> > > > => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.
> > > 
> > > 
> > > OMG this actually worked. Thank you so much friend. I went from trying out the beta to going to old steam client and it immediatly fixed it.
> > 
> > 
> > me too
> 
> This also worked for me.



> > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> 
> This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> 
> By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> 
> I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> 
> Thank you.
> 
> Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> 
> => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.

This still didn't fix my issue, are you able to run me though it via a vc by chance?
![issue](https://user-images.githubusercontent.com/132886116/236771986-e265b155-978f-41e1-adf4-e7a6df268b46.jpg)

**Comment by GalliusG** [comment] 2023-05-08 08:44
> > > > > > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > > > > > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> > > > > 
> > > > > 
> > > > > This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> > > > > By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> > > > > I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> > > > > Thank you.
> > > > > Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> > > > > => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.
> > > > 
> > > > 
> > > > OMG this actually worked. Thank you so much friend. I went from trying out the beta to going to old steam client and it immediatly fixed it.
> > > 
> > > 
> > > me too
> > 
> > 
> > This also worked for me.
> 
> > > Hi all, it has been suggested that this is a bug with the Steam Client beta that was rolled out this week. Opt-out of the Beta appears to fix the issue for some users, but we haven't confirmed that as the fix for all.
> > > If you are still having this issue, give that a shot. If it works, please let us know, so that we can ensure it gets fixed by Valve/Steam before it rolls out to more users.
> > 
> > 
> > This actually worked for me. I have tried JavidPack's solution (which is remove all the players files), the game will load into a character immigration menu but it will crash whenever I click on "New" (as in new character).
> > By opting out of Beta I got the game to load normal again but with 1 downside and that is I can no longer download mods from within the game mod browser. Every time I click on download any kind of mod it will crash the game immediately. But there's a solution for that which is downloading the mod from steam workshop. Bit annoying but the game is working fine now.
> > I'd like to keep this issue opened for any other users that might still have the same problem unsolved to share theirs.
> > Thank you.
> > Update: Upon verifying game file integrity for both Terraria and Tmodloader I was able to download mods within the game's mod browser without crashing behaviors.
> > => Opt out of steam Beta -> Verify game file integrity -> game should run as intended.
> 
> This still didn't fix my issue, are you able to run me though it via a vc by chance? ![issue](https://user-images.githubusercontent.com/132886116/236771986-e265b155-978f-41e1-adf4-e7a6df268b46.jpg)

Step 1: Open your steam
Step 2: Click on "steam" at the top left of your steam overlay
Step 3: Click on settings and it will bring you to "Account". Here you'll see an option called "Beta participation".
Step 4: If you see "steam beta update" then you'll need to click on "CHANGE..." and change your beta participation to "NONE - opt out of all beta programs". This will restart your steam, load into stable steam version and your Tmodloader should run normally. / If your steam is already on NONE then you should check the other solutions above.
(Step 5: if your tmodloader have any further issues you can try verify game file integrity.)

![image](https://user-images.githubusercontent.com/117636245/236778077-8799e32b-fa33-43b4-9fdd-5206a9721e69.png)
![image](https://user-images.githubusercontent.com/117636245/236778580-b200d290-a945-41e3-9e8e-b15430690845.png)
![image](https://user-images.githubusercontent.com/117636245/236778692-cfa607d2-7ed1-42a8-be3b-fcf14b24798d.png)

**Comment by WhineyWaffles** [comment] 2023-05-08 08:51
THANK YOU SO MUCH IT ACTUALLY WORKED THIS TIME! :D i'll verify the files of both and see it if it works if not i'll update again :)

**Comment by cmdrads** [comment] 2023-05-09 11:55
this too fixed the issue for me. I am going to be sad that I have lost the new beta UI but i would much rather be able to play terraria

**Closed as completed** 2023-05-09 18:04 UTC
Labels: Bug, Requestor-Player, Benefit - High, Complexity - Medium

**Comment by JavidPack** [comment] 2023-05-09 20:04
The v2022.09.47.48 release should fix this on tmodloaders end.
