### ISSUE TITLE
Crash when swapping audio Devices when loading in 

### ISSUE THREAD

**Issue by Greengamer077** [bluemagic123/tModLoader#3797] opened 2023-09-07 21:02 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

So im just loading a couple of mods and I hear no sound so i unplug my earphones from my pc. Once that happens the software crashes.

### Log File

[Launch.log](https://github.com/tModLoader/tModLoader/files/12553335/Launch.log)

### Steps to reproduce

1. Start tmod with Earphones plugged in. 2. Unplug Earphones.

### Expected Behavior

When uplugging a Headset it should do nothing but change the audio the game is coming from

### Actual Behavior

it crashes the game

### Reproduction frequency

every time i unplug my earphones (but when i plug them in it cant switch so it doesn't crash)

### Additional Information

EDIT: It just Crashes annytime you unplug anny audio device (i.e. Headphones) even once its dune loading

**Comment by Greengamer077** [comment] 2023-09-07 21:03
ill send the rest of my logs MB.
[client.log](https://github.com/tModLoader/tModLoader/files/12553342/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/12553343/environment.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/12553344/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/12553345/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/12553346/Natives.log)
[server.log](https://github.com/tModLoader/tModLoader/files/12553347/server.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/12553348/terrariasteamclient.log)

**Comment by Greengamer077** [comment] 2023-09-07 21:22
also this is a player issue. it swapped to the modder issue which was weird sence i specified player

**Comment by JavidPack** [comment] 2023-09-25 22:55
duplicate of #2863, will continue tracking this issue over there.

**Closed as not planned by JavidPack** 2023-09-25 22:55 UTC
Labels: Requestor-Modders, NEW ISSUE
