### ISSUE TITLE
tModLoader development on non windows systems

### ISSUE THREAD

**Issue by eldritch-cookie** [bluemagic123/tModLoader#3598] opened 2023-07-04 18:42 UTC
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

tModLoader code as a Contributor/Maintainer

### Description

i have some ideas and am interested in contributing to tmodloader but i don't have a windows vm and would rather prefer to not have to set one up.
there is #1456 but that seems to be about compiling mods on non windows systems.
i've asked around and the patcher uses windows forms so it doesn't run on linux/mac, also no bash/sh script is provided for linux/mac setup.
i would be able and willing to modify/make the patcher to run on linux,
however, i've never contributed a patch to tmodloader before so i am unaware of any details of the development workflow and what features exactly would such a tool need.

### What does this proposal attempt to solve or improve?

it is currently impossible for someone on non windows to contribute to tmodloader. or at least it is not apparent how someone on linux can contribute to tmodloader.

**Comment by Chicken-Bones** [comment] 2023-07-05 00:59
This _is_ a duplicate of #1456, because that is talking about contributing to tModLoader.

There was a lot of discussion in https://discord.com/channels/103110554649894912/883808061578428467 but ultimately not all the challenges were tackled. I'd suggest joining the channel and pinging @ppebb  and @SymphonyDawn3 to ask how far they got and what they key challenges were.

**Closed as completed by Chicken-Bones** 2023-07-05 00:59 UTC
Labels: Requestor-TML Maintainers, Type: Change/Feature Request, NEW ISSUE
