### ISSUE TITLE
Translucent Blue Box Appears Around Minecarts and Mounts 

### ISSUE THREAD

**Issue by jacobwroper** [bluemagic123/tModLoader#2158] opened 2022-02-18 22:26 UTC
### Version

Latest public-1.4-alpha

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When using minecarts or mounts, a blue box appears around the mount/minecart's sprite. The box changes color depending on dye applied. I can't replicate the issue on 1.3 TML, or 1.4 Vanilla Terraria. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8100769/client.log)

### Steps to reproduce

1. Summon a mount or minecart. 

### Expected Behavior

No blue box should be around the mount or minecart. 

### Actual Behavior

A translucent blue box appears  around the mount or minecart. 

### Reproduction frequency

Every time a mount or minecart is used. 

### Additional Information

Graphics card is Radeon Pro Vega 20 4gb. Mac OS is up to date.

**Comment by Chicken-Bones** [comment] 2022-02-20 09:11
Please make sure this occurs with no mods enabled before reporting a bug. Also consider asking in Discord to see if anyone else has seen it or knows what it's caused by/when it started. If it happens with no mods enabled, please send a screenshot.

Is it as simple as just spawning into a world, placing/finding a minecart track and pressing R?

**Comment by jacobwroper** [comment] 2022-02-20 16:28
<img width="2560" alt="Screen Shot 2022-02-20 at 6 50 54 AM" src="https://user-images.githubusercontent.com/47395923/154852875-fd58e1a2-b4ff-40a9-bf3d-f25510ae7e46.png">
[client.log](https://github.com/tModLoader/tModLoader/files/8104409/client.log)

The issue persists even with all mods disabled; screenshot and client log attached. It is as simple as loading into a world and pressing R, either by a track or with a mount equipped.

**Comment by Mirsario** [comment] 2022-03-11 14:25
Closing in favor of the first issue (#1918), though good info here.

**Closed as completed by Mirsario** 2022-03-11 14:25 UTC
Labels: Bug, Requestor-Player
