### ISSUE TITLE
World Gen Error

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2107] opened 2022-01-22 18:57 UTC
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I go to the ocean with the acid in it, it drops into this wierd void which brings me to hell.

### Log File

[17:36:39] [34/INFO] [StatusText]: Drawing map
[17:36:39] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[17:37:49] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[17:37:49] [49/INFO] [StatusText]: Saving map data
[17:37:50] [49/INFO] [StatusText]: Saving world data
[17:37:51] [49/INFO] [StatusText]: Validating world save
[17:38:07] [45/INFO] [Terraria]: Connecting to 51.81.151.250:25611
[17:38:08] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[17:38:09] [45/INFO] [StatusText]: Freeing unused resources
[17:38:09] [45/INFO] [StatusText]: Loading map data
[17:38:09] [45/INFO] [StatusText]: Drawing map
[17:38:09] [45/INFO] [StatusText]: Receiving tile data
[17:38:10] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[17:40:59] [30/INFO] [Terraria]: Connecting to 51.81.151.250:25611
[17:41:00] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[17:41:00] [30/INFO] [StatusText]: Freeing unused resources
[17:41:00] [30/INFO] [StatusText]: Loading map data
[17:41:01] [30/INFO] [StatusText]: Drawing map
[17:41:01] [30/INFO] [StatusText]: Receiving tile data
[17:41:01] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[17:44:34] [48/INFO] [Terraria]: Connecting to 51.81.151.250:25611
[17:44:35] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[17:44:35] [48/INFO] [StatusText]: Freeing unused resources
[17:44:36] [48/INFO] [StatusText]: Loading map data
[17:44:36] [48/INFO] [StatusText]: Drawing map
[17:44:36] [48/INFO] [StatusText]: Receiving tile data
[17:44:37] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[17:45:03] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[17:45:03] [18/INFO] [StatusText]: Saving map data
[17:51:25] [18/INFO] [Terraria]: Connecting to 51.81.151.250:25611
[17:51:25] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[17:51:26] [18/INFO] [StatusText]: Freeing unused resources
[17:51:26] [18/INFO] [StatusText]: Receiving tile data
[17:51:27] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[17:51:29] [18/INFO] [StatusText]: Receiving tile data
[17:51:32] [18/INFO] [StatusText]: Receiving tile data
[17:52:26] [18/INFO] [StatusText]: Receiving tile data
[17:52:43] [18/INFO] [StatusText]: Receiving tile data
[17:52:44] [18/INFO] [StatusText]: Receiving tile data
[17:52:45] [18/INFO] [StatusText]: Receiving tile data
[17:52:50] [18/INFO] [StatusText]: Receiving tile data
[17:52:54] [18/INFO] [StatusText]: Receiving tile data
[17:52:56] [18/INFO] [StatusText]: Receiving tile data
[17:52:58] [18/INFO] [StatusText]: Receiving tile data
[17:53:00] [18/INFO] [StatusText]: Receiving tile data
[17:53:04] [18/INFO] [StatusText]: Receiving tile data
[17:53:45] [18/INFO] [StatusText]: Receiving tile data
[17:53:58] [18/INFO] [StatusText]: Receiving tile data
[17:53:59] [18/INFO] [StatusText]: Receiving tile data
[17:54:01] [18/INFO] [StatusText]: Receiving tile data
[17:54:03] [18/INFO] [StatusText]: Receiving tile data
[17:54:09] [18/INFO] [StatusText]: Receiving tile data
[17:54:13] [18/INFO] [StatusText]: Receiving tile data
[17:54:16] [18/INFO] [StatusText]: Receiving tile data
[17:54:17] [18/INFO] [StatusText]: Receiving tile data
[17:54:22] [18/INFO] [StatusText]: Receiving tile data
[17:54:24] [18/INFO] [StatusText]: Receiving tile data
[17:54:25] [18/INFO] [StatusText]: Receiving tile data
[17:54:31] [18/INFO] [StatusText]: Receiving tile data
[17:54:31] [18/INFO] [StatusText]: Receiving tile data
[17:54:45] [18/INFO] [StatusText]: Receiving tile data
[17:54:52] [18/INFO] [StatusText]: Receiving tile data
[17:55:17] [18/INFO] [StatusText]: Receiving tile data
[17:55:31] [18/INFO] [StatusText]: Receiving tile data
[17:56:21] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[17:56:21] [21/INFO] [StatusText]: Saving map data
[18:19:57] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1017, Fullscreen: False, Display: \\.\DISPLAY1
[18:21:27] [15/INFO] [Terraria]: Connecting to 51.81.151.250:25611
[18:21:28] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[18:21:28] [15/INFO] [StatusText]: Freeing unused resources
[18:21:29] [15/INFO] [StatusText]: Loading map data
[18:21:29] [15/INFO] [StatusText]: Drawing map
[18:21:29] [15/INFO] [StatusText]: Receiving tile data
[18:21:29] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[18:21:41] [15/INFO] [StatusText]: Receiving tile data
[18:21:43] [15/INFO] [StatusText]: Receiving tile data
[18:21:49] [15/INFO] [StatusText]: Receiving tile data
[18:22:01] [15/INFO] [StatusText]: Receiving tile data
[18:22:03] [15/INFO] [StatusText]: Receiving tile data
[18:22:08] [15/INFO] [StatusText]: Receiving tile data
[18:22:15] [15/INFO] [StatusText]: Receiving tile data
[18:22:19] [15/INFO] [StatusText]: Receiving tile data
[18:22:22] [15/INFO] [StatusText]: Receiving tile data
[18:22:25] [15/INFO] [StatusText]: Receiving tile data
[18:22:26] [15/INFO] [StatusText]: Receiving tile data
[18:22:31] [15/INFO] [StatusText]: Receiving tile data
[18:22:33] [15/INFO] [StatusText]: Receiving tile data
[18:23:58] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[18:23:58] [3/INFO] [StatusText]: Saving map data
[18:45:00] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1017, Fullscreen: False, Display: \\.\DISPLAY1
[18:47:33] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1017, Fullscreen: False, Display: \\.\DISPLAY1
[18:48:20] [34/INFO] [Terraria]: Connecting to 51.81.151.250:25611
[18:48:21] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[18:48:21] [34/INFO] [StatusText]: Freeing unused resources
[18:48:21] [34/INFO] [StatusText]: Receiving tile data
[18:48:22] [1/INFO] [Terraria]: Entering world with player: Mover, IsCloud=False
[18:48:43] [34/INFO] [StatusText]: Receiving tile data
[18:48:44] [34/INFO] [StatusText]: Receiving tile data
[18:48:47] [34/INFO] [StatusText]: Receiving tile data
[18:48:47] [34/INFO] [StatusText]: Receiving tile data
[18:48:49] [34/INFO] [StatusText]: Receiving tile data
[18:48:51] [34/INFO] [StatusText]: Receiving tile data
[18:48:53] [34/INFO] [StatusText]: Receiving tile data
[18:48:56] [34/INFO] [StatusText]: Receiving tile data
[18:48:59] [34/INFO] [StatusText]: Receiving tile data
[18:49:04] [34/INFO] [StatusText]: Receiving tile data
[18:49:04] [34/INFO] [StatusText]: Receiving tile data
[18:49:07] [1/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/herosmod/stats.php?tmodversion=0.11.8.6&version=0.3.7.1&platform=w&playhours=1&steamid64=76561198237250676
[18:49:09] [34/INFO] [StatusText]: Receiving tile data
[18:49:10] [34/INFO] [StatusText]: Receiving tile data
[18:49:10] [34/INFO] [StatusText]: Receiving tile data
[18:52:04] [34/INFO] [StatusText]: Receiving tile data
[18:52:11] [34/INFO] [StatusText]: Receiving tile data
[18:52:11] [34/INFO] [StatusText]: Receiving tile data
[18:55:40] [34/INFO] [StatusText]: Receiving tile data
[18:55:40] [34/INFO] [StatusText]: Receiving tile data
[18:55:43] [34/INFO] [StatusText]: Receiving tile data
[18:55:43] [34/INFO] [StatusText]: Receiving tile data
[18:55:44] [34/INFO] [StatusText]: Receiving tile data
[18:55:45] [34/INFO] [StatusText]: Receiving tile data
[18:55:45] [34/INFO] [StatusText]: Receiving tile data
[18:55:48] [34/INFO] [StatusText]: Receiving tile data
[18:55:49] [34/INFO] [StatusText]: Receiving tile data

### Steps to reproduce

1. Get a server at shockbyte
2. add calamity mod and calamity mod music
3. go to the edge of the world

### Expected Behavior

it shouldnt drop into a void

### Actual Behavior

it drops into the void

### Reproduction frequency

every time I restart the server, deleting every file, it still appears.

**Comment by Solxanich** [comment] 2022-01-22 19:44
Please direct your bug report to the Calamity bug reports. https://discord.gg/9kXd2PG
This is almost certainly not a bug with tmodloader - rather a bug specific to Calamity to resolve.

I will be closing this as a mod-specific bug, and no actions available to tmodloader.

**Closed as completed by Solxanich** 2022-01-22 19:44 UTC
Labels: Bug, Requestor-Player
