### ISSUE TITLE
Pickup Text appears in incorrect location for items in the ammo slot

### ISSUE THREAD

**Issue by VortexOfRainbows** [bluemagic123/tModLoader#3144] opened 2022-12-19 02:33 UTC
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When items are in the ammo slot, picking up additional copies of the item will incorrectly spawn popup text.

### Steps to reproduce

1. Pickup an ammo item, have it enter your ammo slot
2. Try picking up the ammo item in a different position
3. Watch as the popup text spawns in the wrong position
4. If you already have the ammo item inside the slot before first picking it up (such as when entering a world), the pickup text will fail to appear on your first pickup.

### Expected Behavior

The popup text should appear above the player, as is the case for normal inventory slot pickups.

### Actual Behavior

The popup text is appearing in the area where the first pickup was grabbed before entering the ammo slot.

### Reproduction frequency

100%

### Additional Information

![AmmoBug](https://user-images.githubusercontent.com/13910999/208336463-ebc25216-37e2-4072-af45-d583e55f4496.gif)

**Comment by JavidPack** [comment] 2023-01-18 19:38
I was able to reproduce this on 1.4-preview, but not 1.4.4 or 1.4-stable. Since 1.4.4 will be the next update, and it works there, I probably won't look into this, since users should be on stable at the moment. Once 1.4.4 becomes preview, we shall revisit this.

**Comment by JavidPack** [comment] 2023-07-03 09:31
I can not replicate on 1.4.4, closing.

**Closed as not planned by JavidPack** 2023-07-03 09:31 UTC
Labels: Bug, Requestor-Player, Benefit - Low, Complexity - Low
