### ISSUE TITLE
Resource pack localization not working

### ISSUE THREAD

**Issue by QuibopWon** [bluemagic123/tModLoader#3782] opened 2023-09-01 21:06 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

renaming things with resource packs just straight up doesn't work on tmod, i have on like 3 resource packs that rename things and none of them are working

![image](https://github.com/tModLoader/tModLoader/assets/85258495/d7797036-77c6-4c71-ab6b-859466f97496)
this volcano should be renamed to fiery greatsword, but it isn't

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12501480/client.log)

### Steps to reproduce

1. get and enable resource pack that changes localization (ie: fiery greatsword is back)
2. check things that should be renamed, see that they aren't

### Expected Behavior

volcano should be renamed to fiery greatsword

### Actual Behavior

volcano is still volcano

### Reproduction frequency

always

**Comment by JavidPack** [comment] 2023-09-01 22:26
Duplicate of #1655

**Closed as not planned by JavidPack** 2023-09-01 22:26 UTC
Labels: NEW ISSUE, Requestor-Player
