### ISSUE TITLE
Textbox keyboards on Steam Deck do not close unless the game is restarted

### ISSUE THREAD

**Issue by TomatoCorey** [bluemagic123/tModLoader#3836] opened 2023-09-24 00:06 UTC
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When a text box and on-screen keyboard pops up (whether that be to name a character or enter a password to join a server) it persists after the "Submit" or "Cancel" buttons are pressed. It draws behind all other menu items and any key presses add text to the box. It takes priority over any other text boxes that may be open, preventing the user from naming a new character or searching for mods by name.
![20230923195459_1](https://github.com/tModLoader/tModLoader/assets/72892698/73540d67-a93f-4806-b64c-d294f1f66723)

![20230923195513_1](https://github.com/tModLoader/tModLoader/assets/72892698/e4bb39d0-511c-49ab-94d8-d873b0276cf7)
![20230923195502_1](https://github.com/tModLoader/tModLoader/assets/72892698/f86d8612-4f10-4676-9951-9de4d3549c13)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12707493/client.log)

### Steps to reproduce

1. Launch the game on SteamOS on a Steam Deck
2. Join a password-protected server OR attempt to name a new character
3. Click "Submit" or cancel
4. Return to the main menu. The textbox will still be in the background

### Expected Behavior

The text box should disappear like it does on every other platform.

### Actual Behavior

The text box doesn't disappear.

### Reproduction frequency

Every single time it happens.

**Comment by JavidPack** [comment] 2023-09-24 02:18
Looks like a duplicate of #3517 , we'll keep tracking this over there.

**Closed as not planned by JavidPack** 2023-09-24 02:18 UTC
Labels: NEW ISSUE, Requestor-Player
