### ISSUE TITLE
Hard limit of wings added by mods

### ISSUE THREAD

**Issue by ChapperNi** [bluemagic123/tModLoader#3195] opened 2023-01-17 07:06 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When enabling multiple mods that add wings, there is a threshold of added wings that cause one of said mods being added to be disabled on startup.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10432222/client.log)

### Steps to reproduce

Add multiple mods that add wings such as Vitality and Calamity Vanities

### Expected Behavior

The game loads with all wings added by mods

### Actual Behavior

The game gives an error on starting up and disables one of said mods that add wings.

### Reproduction frequency

Every single time

**Comment by ilija04** [comment] 2023-01-17 08:19
Duplicate of #1639.

**Closed as not planned** 2023-01-24 19:20 UTC
Labels: Requestor-Modders, NEW ISSUE

**Comment by BforBOY5366** [comment] 2023-01-26 01:31
I would like to point out this has been a problem for a while
