### ISSUE TITLE
PartyZombie NPC to have a replicated loot pool

### ISSUE THREAD

**Issue by justreq** [bluemagic123/tModLoader#2175] opened 2022-03-03 04:06 UTC
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A loot pool to PartyZombie that automatically replicates a particular vanilla NPC loot pool. That's pretty much it

**Comment by Solxanich** [comment] 2022-03-03 04:35
Possible duplicate of #2174  due to mismatched timing.
Please confirm.

**Comment by justreq** [comment] 2022-03-03 04:37
> Possible duplicate of #2174  due to mismatched timing.
> 
> Please confirm.

Yea it is, didn't see that one

**Closed as completed** 2022-03-04 22:57 UTC
Labels: Requestor-Modders, Type: Change/Feature Request
