### ISSUE TITLE
No sound in tmodloader

### ISSUE THREAD

**Issue by SilveonSenpai** [bluemagic123/tModLoader#2916] opened 2022-09-11 11:18 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

No sound from game, a lot of people having the same issue

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9542354/client.log)

### Expected Behavior

Normal sound from the game

### Actual Behavior

No sound(

**Comment by Chicken-Bones** [comment] 2022-09-15 01:18
Duplicate of #2797, please try the workaround in my comment there

**Closed as not planned by Chicken-Bones** 2022-09-15 01:18 UTC
Labels: Bug, NEW ISSUE, Requestor-Player
