### ISSUE TITLE
tModLoader Doesn't Recognize Localization File in My Resource Pack

### ISSUE THREAD

**Issue by MysticalPlane** [bluemagic123/tModLoader#3570] opened 2023-06-21 16:06 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I've created a custom resource pack for personal playthroughs of the game. It loads properly, shows all the changes EXCEPT the localization.

I've painstakingly changed a lot of words in there. Vanilla Terraria works perfectly, but with Calamity Mod and few others turned on in tModLoader, it's just not overwriting the localization file.

I have the same resource pack in my vanilla folder. I only have 1 resource pack in vanilla and 1 in tModLoader, both created by myself.

Images and Music folders work, but not the Localization folder. Please help! I've tried so many things, but nothing's working! If Vanilla works, why not tModLoader?

(It's named as en-US.csv in the folder) 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11820129/client.log)

### Steps to reproduce

1. Create a new resource pack.
2. Populate the folder with Images, Music, and Localization.
3. Add custom images and music.
4. Take the en-US.csv from the Terraria forum.
5. Rename Bug Net to Critter Net and save the file.
6. Open up tModLoader and select your resource pack.

### Expected Behavior

tModLoader should also load the Localization folder, just as how it's perfectly loading the Images and Music folders in a resource pack.

### Actual Behavior

The Localization file never gets used in the game. My file works fine in Vanilla Terraria.

### Reproduction frequency

Every single time.

### Additional Information

I've tried so many things, but nothing's working. Super sad about it.

**Comment by direwolf420** [comment] 2023-06-21 16:25
Duplicate of #2615

**Comment by MysticalPlane** [comment] 2023-06-21 16:27
Got it.

**Closed as not planned** 2023-06-21 17:05 UTC
Labels: NEW ISSUE, Requestor-Player

**Comment by MysticalPlane** [comment] 2023-06-21 17:06
I’m fine with it. I was able to download a mod from Cyril and fixed it! :)
