### ISSUE TITLE
Main Engine Crash: Unable to Load LogitechLedEnginesWrapper.dll

### ISSUE THREAD

**Issue by AudiaUser999** [bluemagic123/tModLoader#4244] opened 2024-06-02 00:14 UTC

**Comment by AudiaUser999** [comment] 2024-06-02 02:05
I fixed the issue by removing LogitechLedEnginesWrapper.dll

**Comment by partisani** [comment] 2024-06-02 19:23
Looks like the dll for the dynamic keyboard rgb stuff is missing, try reinstalling tModLoader/Terraria and trying again

**Comment by direwolf420** [comment] 2024-06-03 15:15
Duplicate of #4241, see the solution linked there

**Closed as completed** 2024-06-04 01:17 UTC
Labels: Requestor-Modders, NEW ISSUE
