### ISSUE TITLE
Server config loading modpacks incorrectly (?)

### ISSUE THREAD

**Issue by Darkmega18** [bluemagic123/tModLoader#4332] opened 2024-08-03 06:13 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When I'm loading my server I discovered the server config. So I configured my file paths properly and such but at the bottom it asks for modpack.
But while watching the console tries to load a json with the name of the modpack and then fails to do so due to the ingame modpack maker creating a folder with hard copies of the mods and an enabled.json file, not just a file with the modpack's name.

I stopped it soon after to try to figure out what it was doing. Forgotten feature?

While you're at it:
somewhere in the config the bat file is also saying my slashes for my filepaths are around the wrong way... when I literally copied them out of my file browser with the right slashes and double checked them in the config itself. it's whack.

### Log File

[server.log](https://github.com/user-attachments/files/16478290/server.log)

### Steps to reproduce

1. Configure serverconfig based on intructions left inside the file in the comments.
2. Try to load a server using a modpack created from ingame using the config at the bottom.
3. Have issues.

### Expected Behavior

That it should know how it'd own modpacks are made and how to launch them?

### Actual Behavior

but it doesn't.

### Reproduction frequency

yep.

### Additional Information

I'm not sure if maybe this config file is just really old and has been sitting here for an extended period of time cause I've had tmodloader installed for years and so maybe something changed with the intended instructions? but it asked for a modpack name, so I just gave it the modpack name. :V

[serverconfig.txt](https://github.com/user-attachments/files/16478329/serverconfig.txt)
heres the server config in question, if you want to look over it.

Further, why on earth is the server trying to load a bunch of old versions of the mods? does tmodloader keep old versions of the mods in the steam files somewhere? I found that a little whack too.

**Comment by JavidPack** [comment] 2024-08-06 19:31
Duplicate of https://github.com/tModLoader/tModLoader/issues/4063, you'll find a workaround for this issue mentioned in that issue as well.

**Closed as not planned by JavidPack** 2024-08-06 19:31 UTC
Labels: NEW ISSUE, Requestor-Player

**Comment by Darkmega18** [comment] 2024-08-08 06:19
oh, welp. thanks.
