### ISSUE TITLE
Crashing on Start-Up with "System.NullReferenceException: Object reference not set to an instance of an object" Error

### ISSUE THREAD

**Issue by cmdrads** [bluemagic123/tModLoader#3463] opened 2023-05-08 18:48 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

with or without mods, with or without players, saves, worlds, etc, the game crashes on launch no matter what I do. If I wipe my saves and have no mods, the game makes it to the main menu, but when I click "New" in the character select menu, the game instantly crashes. If I have any save files (worlds, players) or any mods what so ever, the game doesn't make it past the Relogic Screen. I have tried everything! Wiping all of the data in documents and in the install location, restarting my PC, disabling any kind of firewall and disabling steam cloud before wiping everything and launching. NOTHING works. and its the same error every time. I will attach every single log I have to help you solve this. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11424204/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/11424205/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/11424206/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/11424207/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/11424208/terrariasteamclient.log)

### Steps to reproduce

With no saves or mods:

1. Launch Game
2. Try to create a character
3. Game Crash

With any saves or mods present:
1. Launch Game
2. Crashes after the relogic logo

### Expected Behavior

Expected behaviour is for the game to allow me to either load my character, or at least make a new one

### Actual Behavior

actual behaviour is the game having a main engine crash with the error message stated in the title, and in the logs.

### Reproduction frequency

I can reproduce this error consistently, it is a constant issue.

**Comment by cmdrads** [comment] 2023-05-08 18:59
https://user-images.githubusercontent.com/107015203/236909072-ba56abb1-210f-499d-8013-ee05ab913840.mp4


https://user-images.githubusercontent.com/107015203/236909077-80d322db-a556-4b26-a622-01a0290ea92f.mp4

Here I have uploaded videos of the behaviour described in my issue

**Comment by JavidPack** [comment] 2023-05-09 00:26
Duplicate of #3456

**Closed as not planned by JavidPack** 2023-05-09 00:26 UTC
Labels: NEW ISSUE, Requestor-Player
