### ISSUE TITLE
HttpRequests completely broken on TModLoader Server for Linux

### ISSUE THREAD

**Issue by xNarnia** [bluemagic123/tModLoader#3126] opened 2022-12-07 23:58 UTC
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Using the latest version of TModLoader Server
When I create an HttpClient and perform an HttpRequest
Then the plugin fatally errors

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/10180956/server.log)

### Steps to reproduce

1. Create a brand new mod.
2. Execute the below code somewhere. (I overrode the Load() method and ran it there)

```
var client = new HttpClient();
var url = new Uri("https://raw.githubusercontent.com/xPanini/TCR-TerrariaChatRelay/master/TCR-TModLoader/TerrariaChatRelay/build.txt");
var data = client.GetAsync(url).Result;
```

### Expected Behavior

The request should come back with the contents of the URL specified. In my example, it is a single line file with a version number in it.

### Actual Behavior

The plugin is fatally exiting, stopping all further action from the plugin.

### Reproduction frequency

Reproducible everytime.

### Additional Information

It is extremely important to note that **this works fine on Windows**.
I have tested this bug on Debian 11 and Ubuntu 22.10 and both error the same.

The below code may be of interest since it involves searching for _System.Net.Http.HttpConnectionPoolManager's SendAsyncCore_.
It is worth noting that _Logging.tML.Warn("HttpWebRequest send/submit method not found");_ does NOT appear in the logs. 
https://github.com/tModLoader/tModLoader/blob/c51c8f832ccd52311f81a628ffbf4df3bb775bbe/patches/tModLoader/Terraria/ModLoader/Engine/LoggingHooks.cs#L75-L96

**Comment by Chicken-Bones** [comment] 2022-12-08 00:26
Duplicate of https://github.com/tModLoader/tModLoader/issues/3073

**Closed as not planned by Chicken-Bones** 2022-12-08 00:26 UTC
Labels: Requestor-Modders, NEW ISSUE
