### ISSUE TITLE
1.4.4 Preview Not Launching on MacOS

### ISSUE THREAD

**Issue by CausticWarrior** [bluemagic123/tModLoader#3337] opened 2023-03-22 19:44 UTC
### Version

1.4.4 preview

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When switching to the newest 1.4.4 preview, the game crashes before it can load.
[client.log](https://github.com/tModLoader/tModLoader/files/11044146/client.log)

### Log File

Up above

### Steps to reproduce

1: Be on a Mac
2: Go to preferences and select Betas - 1.4.4 preview

### Expected Behavior

Load

### Actual Behavior

Crash

### Reproduction frequency

100%

### Additional Information

My Mac:
16 GB memory
M1 Chip
Mac Mini

**Comment by direwolf420** [comment] 2023-03-22 22:05
Duplicate of #3093

**Closed as not planned** 2023-03-27 16:56 UTC
Labels: NEW ISSUE, Requestor-Player

**Comment by Chicken-Bones** [comment] 2023-03-28 21:59
Fixed in d728de6b694815fa0072f28c452a3dc61d1e2c9b
