### ISSUE TITLE
Crash "Index was out of bounds" Finalize sound

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3765] opened 2023-08-27 13:18 UTC
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When doing nothing, ~~i think just hovering over some buttons it the menu~~ not even that just random
VERY QUICKLY, it will crash

### Log File

Github is too trash to let me upload logs, so here's google drive:
https://drive.google.com/file/d/1TAYF0Z0Jxmjcz7jRmpaI_zeuEX9Es5Ab/view?usp=sharing

### Steps to reproduce

1. Start Game
2. Random Crash

### Expected Behavior

Work

### Actual Behavior

Crash

### Reproduction frequency

Always

### Additional Information

This is on steam deck

If a mod caused the crash, it shouldn't crash the game, or at least tell the user what mod caused the crash

**Comment by JavidPack** [comment] 2023-08-29 18:07
This looks like an issue with the TerrariaAmbienceAPI mod. Do you get a crash with 0 mods enabled?

**Comment by ghost** [comment] 2023-08-30 21:52
After disabling all mods, it didnt crash after some doing stuff in the menu, but i can't really say if it was the mod, since it can take really a while before it crashes, but sometimes its also very quick, like before it finished loading all mods it crashed becuase of that error

and after enabling it, my game started to lag in the menu sometimes, and after another reload (after entering and leaving a world)
it froze in the "Unloading Mod: Terraria Ambience v0.2.6.2"

with no crashes, so thats wierd
but it may have been it, i'll test some more

**Comment by JavidPack** [comment] 2023-11-30 18:46
From a number of support threads in the Discord, I'm assuming this issue was caused by Terraria Ambience mod. Closing for now, feel free to come by Discord if you have other support issues.

**Closed as not planned by JavidPack** 2023-11-30 18:46 UTC
Labels: Requestor-Player
