### ISSUE TITLE
ModItem.UseItem is not called for last item in stack?

### ISSUE THREAD

**Issue by FenixFyreX** [bluemagic123/tModLoader#100] opened 2017-01-10 19:55 UTC
It seems that when a consumable modded item's stack value is 1, and you use it (`item.createTile`, or simply consume upon right click), `ModItem.UseItem` does not get called. I've been attempting to implement some form of OnPlaceTile callback for placeable ModItems, but I cannot do it in an easy way due to this callback failing on the last item of a stack. I've created a temporary workaround with a few more variables, but it's hacky at best and I'd like to see this oversight fixed.

If the code for reproduction is necessary I'll upload it, although it isn't hard to reproduce. Simply create a comsumable ModItem upon use, override it's `UseItem` method to print some text via `Main.NewText`, and see the magic...not happen :P

**Comment by JavidPack** [comment] 2017-01-29 23:08
Looks like we need to be more explicit on the limitations and use cases of UseItem.

After some testing (seeing that it does work for items it was designed for) and seeing that you figured it out, I think I'll close this.

**Closed by JavidPack** 2017-01-29 23:08 UTC
Labels: Bug
