### ISSUE TITLE
[1.4] Deerclops' ice spikes attack sounds are too low

### ISSUE THREAD

**Issue by Polaritz** [bluemagic123/tModLoader#2543] opened 2022-06-11 22:25 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Deerclops ice spikes attack sound is hardly audible

### Steps to reproduce

1. spawn deerclops
2. wait until it uses ice spike attack

### Expected Behavior

Ice spike attack sounds play normally

### Actual Behavior

Ice spike attack sounds are way too low compared to vanilla

### Reproduction frequency

always

**Comment by Mirsario** [comment] 2024-06-24 17:14
Cannot reproduce in modern TML, the volume is exactly the same as in vanilla. Perhaps someone fixed this and forgot to close the issue.

**Closed as completed by Mirsario** 2024-06-24 17:14 UTC
Labels: Bug, Requestor-Player, Benefit - Low, Complexity - Low
