### ISSUE TITLE
i cant look at the mod packs section without it crashing tmod loader

### ISSUE THREAD

**Issue by ralfie171** [bluemagic123/tModLoader#2900] opened 2022-09-05 20:53 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i open mod packs it only shows the first mod pack i did wich had about 11 mods in it then when it trys to load the other 2 it just crashes with no warning

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9491926/client.log)

### Steps to reproduce

i open tmod loader
open workshop
click modpacks
game crashes instantly

### Expected Behavior

it should just open the mod packs section

### Actual Behavior

it says a fatal error has happened and then it says some code and stuff i dont understand

### Reproduction frequency

every time i open the mod packs section it crashes in like half a second

**Comment by JavidPack** [comment] 2022-09-09 06:12
Thanks for the report, I'll see what I can do.

**Comment by JavidPack** [comment] 2022-09-09 06:13
Duplicate of #2701 , will be tracked there

**Closed as completed by JavidPack** 2022-09-09 06:13 UTC
Labels: Bug, Requestor-Player
