### ISSUE TITLE
Crash when disabling/switching audio.

### ISSUE THREAD

**Issue by cyraid** [bluemagic123/tModLoader#3956] opened 2023-12-01 20:30 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When my bluetooth headset turns off while the game is open, it completely closes/crashes. I have noticed this line popping in (`Natives.log`) up after the fact, I'm not sure if it's relevant, but:
```
Assertion failed: !FAILED(hr) && "Failed to get IAudioClient current padding!", file C:\Games\Terraria\tModLoader\FNA\lib\FAudio\src\FAudio_platform_win32.c, line 186
```

### Steps to reproduce

1. Launch Terraria with Sound.
2. Disable current audio / unplug / power off bluetooth headset.
3. Witness game closing/crash.

### Expected Behavior

No crash, possibly just disable sound like natural Terraria does.

### Actual Behavior

Crash.

### Reproduction frequency

100%

**Comment by BlinDeex** [comment] 2023-12-01 20:38
Having identical issue with identical error appearing in logs with bluetooth headset as well. Sound just doesnt appear when you turn on with the game open either but cant spot anything relating to this in logs

**Comment by JavidPack** [comment] 2024-01-09 00:04
Duplicate of #2863, we will continue tracking the issue there.

**Closed as not planned by JavidPack** 2024-01-09 00:04 UTC
Labels: NEW ISSUE, Requestor-Player
