### ISSUE TITLE
New 1.4-stable update makes the game not launch on linux

### ISSUE THREAD

**Issue by 3pical** [bluemagic123/tModLoader#2660] opened 2022-07-01 09:52 UTC
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Clicking the play button launches tmodloader, after a few seconds tmodloader closes.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9027897/client.log)

### Steps to reproduce

1. press play on latest tmodloader 1.4-stable release

### Expected Behavior

Launching Tmodloader and havin a blast

### Actual Behavior

Not launching Tmodloader and not havin a blast

### Reproduction frequency

very frequently, 100% even!

### Additional Information

Os is Fedora 36. Steam is RPM

**Comment by jonatjano** [comment] 2022-07-01 11:03
same issue on for me 
> Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

steam installed via apt 
![image](https://user-images.githubusercontent.com/17279801/176882219-e8ff79b1-cb52-4fb0-b96e-09fd81606a8e.png)

there are no tmodloader specific log in the terminal

**Comment by NaitLee** [comment] 2022-07-01 11:59
I can confirm too. Symptom here: the starter script just exits, after the line `Launched Using Local Dotnet`.

In `tModLoader/tModLoader-Logs/Natives.log`:

```
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Error:
  An assembly specified in the application dependencies manifest (tModLoader.deps.json) was not found:
    package: 'Steamworks.NET', version: '20.1.0'
    path: 'runtimes/linux-x64/lib/netstandard2.1/Steamworks.NET.dll'
```

In `tModLoader/Libraries`, the folder `Steamworks.NET` isn't present, in contrast to previous version.  
(The former error doesn't matter, I think.)

Edit: by restoring it, error is still there. maybe I'm missing something else
PS. I browsed the commit history and see [this commit](https://github.com/tModLoader/tModLoader/commit/fa590b2d1614460918ca9c5d03a3fbfcbf762e8d) about [here of this file](https://github.com/tModLoader/tModLoader/blob/fa590b2d1614460918ca9c5d03a3fbfcbf762e8d/patches/tModLoader/Terraria/Terraria.csproj.patch#L46). maybe the problem but just guess...

**Comment by FREEZEball** [comment] 2022-07-01 14:28
My `Natives.log`:

> Error:
>   An assembly specified in the application dependencies manifest (tModLoader.deps.json) was not found:
>     package: 'Steamworks.NET', version: '20.1.0'
>     path: 'runtimes/linux-x64/lib/netstandard2.1/Steamworks.NET.dll'

`Launch.log`:

> Verifying .NET....
> pid 7056 != 7047, skipping destruction (fork without exec?)
> Logging to /home/fb/.local/share/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
> pid 7058 != 7047, skipping destruction (fork without exec?)
> Fixing .NET SDL PATH issues
> pid 7063 != 7047, skipping destruction (fork without exec?)
> Success!
> pid 7067 != 7047, skipping destruction (fork without exec?)
> Parsing .NET version requirements from runtimeconfig.json
> pid 7069 != 7047, skipping destruction (fork without exec?)
> Success!
> pid 7073 != 7047, skipping destruction (fork without exec?)
> Checking for old .NET versions to remove from folder
> Cleanup Complete
> Checking dotnet install...
> Dotnet should be present in "/home/fb/.local/share/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
> pid 7075 != 7047, skipping destruction (fork without exec?)
> Launched Using Local Dotnet
> pid 7090 != 7047, skipping destruction (fork without exec?)

Using older release works.

**Comment by P-Ramos16** [comment] 2022-07-01 17:55
MANAGED TO MAKE IT WORK:
-Delete Libraries folder (in steam files);
-Verify Integraty of game files;
-Start game.

Worked on my machine running manjaro with 5.15 kernel.
Good Luck!

**Comment by FREEZEball** [comment] 2022-07-01 18:16
~~Per @P-Ramos16~~
> MANAGED TO MAKE IT WORK: 

~~Hasn't worked for me using arch 5.18.7. Same exact messages in logs as in my last message.~~

Apparently, this last update caused problems for [a lot of people](https://steamcommunity.com/app/1281930/discussions/), on Windows too.

15-minute edit: Worked after I set `start-tModLoader.sh` executable.

**Comment by 3pical** [comment] 2022-07-01 18:17
> MANAGED TO MAKE IT WORK: -Delete Libraries folder (in steam files); -Verify Integraty of game files; -Start game.
> 
> Worked on my machine running manjaro with 5.15 kernel. Good Luck!

How on earth do you even think of doing this, why does this work, why do Tmodloader devs not fix this.

**Comment by Solxanich** [comment] 2022-07-01 18:41
We are actively looking in to it, but does make it sound like Steam failed to deliver the update correctly.
Which is hard for us to fix directly

**Comment by Solxanich** [comment] 2022-07-01 18:49
Further if anyone can provide a copy of the entirety of the Libraries folder, we might be able to try and fix this, 
Because it very much seems hard to fix Steam not handling the files correctly without a direct copy of the 'bad files' to fix from

**Comment by FREEZEball** [comment] 2022-07-01 19:03
[Archive 2.zip](https://github.com/tModLoader/tModLoader/files/9031090/Archive.2.zip)
[Archive 1.zip](https://github.com/tModLoader/tModLoader/files/9031091/Archive.1.zip)

@Solxanich, here you go, had to split it in two. Archlinux, steam-runtime.

I had to downgrade my steam version to v2022.05.103.34 from github releases, then validated game files and updated it to acquire same logs as before. You might also need those libraries someone else who only updated and hasn't screw around with the game as much as I have today.

**Comment by FREEZEball** [comment] 2022-07-01 19:09
> % diff --recursive "/home/fb/.local/share/Steam/steamapps/common/tModLoader/Libraries/" "/home/fb/Desktop/Archive/"
> Only in /home/fb/.local/share/Steam/steamapps/common/tModLoader/Libraries/: steamworks.net
> Only in /home/fb/Desktop/Archive/: Steamworks.NET

There we go, there is our problem. ~~If you manually rename `tModLoader/Libraries/Steamworks.NET` to `tModLoader/Libraries/steamworks.net` in a freshly updated copy of the game, it works.~~ ~~Edit: No, the whole structure of the library changed, gotta delete it and validate. But the problem seems to be in this library.~~ Edit 2: the problem is with both, see my next post.

**Comment by Solxanich** [comment] 2022-07-01 19:28
Hmm. Ok, yes, the Steamworks.NET library is the issue.
Windows isn't case sensitive so it wouldn't have shown up until it hit Linux, and Steam doesn't fix capitalization on its update deployments so it could be any combination of the files within there that existed before.
Or other files.

**Comment by FREEZEball** [comment] 2022-07-01 19:33
Yes, the problem is with case-sensitivity AND new files in the library. Updating from v2022.05.103.34 to v2022.06.96.1 creates this:
![image](https://user-images.githubusercontent.com/11259935/176957775-fdc7815b-a913-429a-92d7-a4d24475ef05.png)
(not the case for folder name - `Steamworks.NET`)
And working version validated by steam is creating structure like this: 
![image](https://user-images.githubusercontent.com/11259935/176958040-678a7f92-5b8e-42f6-9647-83f77f30833c.png)

Log from my first post indicated it, actually:

> Error:
> An assembly specified in the application dependencies manifest (tModLoader.deps.json) was not found:
> package: 'Steamworks.NET', version: '20.1.0'
> path: 'runtimes/linux-x64/lib/netstandard2.1/Steamworks.NET.dll'

@Solxanich for easier debugging could you add more upper directories into log so it is `path: 'tModLoader/Libraries/steamworks.net/20.1.0/runtimes/linux-x64/lib/netstandard2.1/Steamworks.NET.dll'` not `path: 'runtimes/linux-x64/lib/netstandard2.1/Steamworks.NET.dll'`? Would've helped catch the problem quicker in this situation.

**Comment by Solxanich** [comment] 2022-07-01 19:37
ok, I can get the rename fixed and the extra file removed and push an update to fix that during launch scripts pretty quickly at this juncture.

With respect to path - that's automatic output of .NET C#. I unfortunately do not have control over that.

It's unfortunate this wasn't caught when it was tested on linux in general. I don't how it didn't get caught than prior to adding to the codebase.

**Comment by FREEZEball** [comment] 2022-07-01 19:41
> It's unfortunate this wasn't caught when it was tested on linux in general. I don't how it didn't get caught than prior to adding to the codebase.

My guess is it was tested as a fresh install, not an update of a previous version, or using a filesystem that ignores case-sensitivity. Anyways, great job by everyone in this thread.

Now just gotta wait for when Calamity updates :smile:

**Comment by P-Ramos16** [comment] 2022-07-01 19:49
> 

Having 3 people waiting for me to start our world at the same time makes you do desperate things. Also a very old post somewhere mentioned issues with library files so I gave it a try.

Heres my old Libraries folder vs new ones (had to seperate the two for the 25mb limit):

New:
[Libraries1.zip](https://github.com/tModLoader/tModLoader/files/9031268/Libraries1.zip)
[Libraries2.zip](https://github.com/tModLoader/tModLoader/files/9031267/Libraries2.zip)
Old:
[LibrariesOld1.zip](https://github.com/tModLoader/tModLoader/files/9031274/LibrariesOld1.zip)
[LibrariesOld2.zip](https://github.com/tModLoader/tModLoader/files/9031273/LibrariesOld2.zip)

**Comment by Solxanich** [comment] 2022-07-01 20:00
I've pushed the fix based on FreezeBall's information.
https://github.com/tModLoader/tModLoader/commit/9fde4f227b7a6e1fb261345688a2a4000b203bbd

It will be about twenty minutes before it hits steam as playable.

In the short term, please use the following workaround, and DO NOT use Proton:
![image](https://user-images.githubusercontent.com/59670736/176961433-a78d3ec1-4a03-4d8f-b612-1b7bf1627249.png)

**Closed as completed** 2022-07-01 21:08 UTC
Labels: Bug, Requestor-Player
