### ISSUE TITLE
Lava bubbling sound plays when quitting out of world and persists until game close

### ISSUE THREAD

**Issue by Hexzatite** [bluemagic123/tModLoader#2488] opened 2022-06-03 07:02 UTC
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When leaving a world, any world, there is a bubbling lava noise that plays once the menu loads, and this persists infinitely until the game is closed. Nothing removes the noise other then this. No mods need to be enabled for this to occur.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8830238/client.log)

### Steps to reproduce

1. Enter a world, any world with any character
2. Quit the world

### Expected Behavior

The menu to open up and there not be lava bubbling noise.

### Actual Behavior

When leaving the world, right as the menu loads, a lava bubbling noise starts to play on repeat forever.

### Reproduction frequency

I was able to reproduce this 100% of the time. Regardless of making a new world, character, or reinstalling tModLoader.

### Additional Information

The noise persists even when reentering a world. Furthermore, doing it multiple times actually causes the sound to stack on top of each other, creating a right mess of sound.
I am on Arch Linux v5.18.1 and use PipeWire v1:0.3.51-1, if it is of any help.

Here is a recording, in case one was needed to help diagnose this since this is probably weird to explain:
https://user-images.githubusercontent.com/10444481/171803267-f899fb16-0d2f-4d1e-9b50-02f46a6bcb14.mov

**Comment by JavidPack** [comment] 2022-06-03 07:45
duplicate of #2429

**Closed as completed by JavidPack** 2022-06-03 07:45 UTC
Labels: Bug, Requestor-Player
