### ISSUE TITLE
Teleport sound effect

### ISSUE THREAD

**Issue by Turbanik** [bluemagic123/tModLoader#3282] opened 2023-03-01 18:13 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Whenever you use magic mirror or recall potion, the sound is broken

**Comment by Mirsario** [comment] 2023-03-01 19:23
Duplicate of #2575

**Closed as not planned by Mirsario** 2023-03-01 19:23 UTC
Labels: Requestor-Modders, NEW ISSUE
