### ISSUE TITLE
TML not running claims steam isnt running.

### ISSUE THREAD

**Issue by PublicVoidUpdate** [bluemagic123/tModLoader#2831] opened 2022-08-13 02:15 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

My Terraria path is 'D:\SteamLibrary\steamapps\common\Terraria' and everytime i try to run TML it gives me the issue of Steam not being open and/or installed despite the fact it is open and running as my active window. The prompt is "Please ensure Steam is logged in and running". (This being the manual install of TML because the Steam version would not download for whatever reason.) I am "Borrowing" (Family share through steam) terraria. Any help is appreciated. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9330590/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9330591/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9330592/Natives.log)

### Steps to reproduce

Installed latest release in same folder as terraria, (Terraria.exe and start-tModLoader.bat in the same directory)

### Expected Behavior

TML should load and display opening GUI

### Actual Behavior

"Please ensure Steam is logged in and running"  See attached Log

### Reproduction frequency

unable to not reproduce it

**Comment by Chicken-Bones** [comment] 2022-08-13 03:18
Duplicate of pinned issue #881

Family share doesn't work. You need to buy Terraria. We've contacted valve many times but no help.

**Closed as completed by Chicken-Bones** 2022-08-13 03:18 UTC
Labels: Bug, Requestor-Player

**Comment by PublicVoidUpdate** [comment] 2022-08-13 04:03
I read that manual install should work on the main (referenced) thread, this is what I did and it still didnt work. the comments are 2yrs old, so I guess an update might have broken that. Is it still possible over manual?

**Comment by Chicken-Bones** [comment] 2022-08-15 17:36
I don't think that workaround was ever officially approved. I don't remember it working myself.
