### ISSUE TITLE
tModLoader v2022.8.54.6 Fatal Error

### ISSUE THREAD

**Issue by 8BitBunnie** [bluemagic123/tModLoader#2988] opened 2022-09-27 23:27 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I was told to send this here, starting tModLoader crashes and gives me this error 
![image](https://user-images.githubusercontent.com/114538991/192654851-0f92edf8-75e7-49aa-be83-ac17ac13db47.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9660179/client.log)

### Steps to reproduce

1. Launch tModLoader
2. Be angry that you can't play tModLoader

### Expected Behavior

The game launches and I get to play

### Actual Behavior

The game instantly crashes

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment] 2022-09-27 23:59
See https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#multiple-extensions-for-asset

Duplicate of #2913

**Closed as not planned by JavidPack** 2022-09-27 23:59 UTC
Labels: NEW ISSUE, Requestor-Player
