### ISSUE TITLE
Audio on M1 mac sounds compressed

### ISSUE THREAD

**Issue by Virusnest** [bluemagic123/tModLoader#2720] opened 2022-07-16 09:31 UTC
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Terraria Audio sounds compresed inlcuding music and sound effects

### Reproduction frequency

100%

**Comment by Chicken-Bones** [comment] 2022-09-15 23:20
Duplicate of #2118

**Closed as not planned by Chicken-Bones** 2022-09-15 23:20 UTC
Labels: Bug, NEW ISSUE, Requestor-Player
