### ISSUE TITLE
Add a hook for manually setting a filter/category type to an item for use in the Duplication Menu

### ISSUE THREAD

**Issue by JackerAcid** [bluemagic123/tModLoader#4106] opened 2024-03-13 06:22 UTC
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

A new hook called (`ModifyItemEntryFilter` or `ModifyItemFilter`) that would allow for modders to manually set their item to any filter/category in the Duplication Menu.

### What does this proposal attempt to solve or improve?

It is currently impossible to manually set an item's filter/category without **detouring** the `Terraria.GameContent.Creative.On_ItemFilters.<Filter/Category>.FitsFilter` method. For say making your modded item go under the "Tools" filter in the Duplication Menu.

![image](https://github.com/tModLoader/tModLoader/assets/93073858/138bbdde-633e-48b4-b339-c040f454f850)

### Which (other) solutions should be considered?

Could also be a `SetStaticDefaults` or `SetDefaults` thing

**Comment by JavidPack** [comment] 2024-03-13 06:28
As discussed on Discord, I think the main category that modders would want to add to is Tools. Every other category is derived almost solely by item fields, but Tools has a set of itemids that additionally fit the filter. Exposing that as a ItemID.Set would be the easiest solution to implement. If there is interest in customizing all filters from the community, that could be done but will be more effort in the end.

If you have input to this suggestion on how you would want to use it, please comment below. Also note that the existing ModifyResearchSorting hook controls the sorting within the results, allowing similar items to be grouped in the results, it does not affect which Filter an item belongs to.

**Comment by direwolf420** [comment] 2024-03-14 10:58
Duplicate of #2921

**Closed as completed** 2024-04-08 21:24 UTC
Labels: Needs Discussion, Type: Change/Feature Request, Requestor-Player
