### ISSUE TITLE
Entering the modpacks section crashes the game.

### ISSUE THREAD

**Issue by DerplingDev** [bluemagic123/tModLoader#2568] opened 2022-06-17 17:31 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Upon clicking on the Modpacks button in the Workshop menu, the game crashes most of the time. When it does not crash, it is almost impossible to make a modpack without error.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8929485/client.log)

### Steps to reproduce

1. Enable mods to put in modpack.
2. Navigate to modpacks button and click it.
3. Game crashes, if not, creating a modpack with said mods will likely not work.

### Expected Behavior

Modpacks UI should show up and should not crash the game. Creating modpacks should not leave errors and the modpacks should not be malformed and should be usable.

### Actual Behavior

Modpacks UI does not show up most of the time and the game crashes upon trying the enter the modpacks section. Other times, when it does load, creating a modpack is not possible, giving an error about how a certain mod's config already exists. When this happens, it leaves you on the name selection for the modpack. When trying to cancel the name selection, sometimes the game will crash with the same error as simply clicking the modpacks button.

### Reproduction frequency

The crash happens about 90% of the time, the modpack creation issue happens only with certain mods enabled. However, the game will still most likely crash when making the modpacks successfully after creation.

### Additional Information

The crash still occurs even with no mods enabled and the modpack creation issue was only fixed when I had next to no mods enabled, likely due to the amount of configs that needed to be copied being relatively low. Also, let me know if you need the error that is given when the modpack fails to create and I can give it to you.

**Comment by JavidPack** [comment] 2022-09-09 06:15
duplicate of #2701 , will track there

**Closed as completed by JavidPack** 2022-09-09 06:15 UTC
Labels: Bug, Requestor-Player
