### ISSUE TITLE
tModLoader v2022.9.47.30 Fatal Error

### ISSUE THREAD

**Issue by Jensay** [bluemagic123/tModLoader#3314] opened 2023-03-16 18:55 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I try to load tModLoader it opens a cmd window, with some quickly scrolling text, before closing and giving me an error window.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10994844/client.log)

### Reproduction frequency

Every time I try to start tModLoader.

### Additional Information

I have since tried uninstalling both tModLoader and Terraria. Did a reinstall of Terraria, booted it and closed it then installing tModloader and trying to load that. Still get the same error.
[client.log](https://github.com/tModLoader/tModLoader/files/10995020/client.log)

Update: I can launch tModLoader in 1.3 Legacy beta but i cannot get it to launch in the default or 1.4 preview beta's.

**Comment by JavidPack** [comment] 2023-03-17 00:58
This issue is covered in the FAQ: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#multiple-extensions-for-asset

Duplicate of #2913

**Closed as not planned by JavidPack** 2023-03-17 00:58 UTC
Labels: NEW ISSUE, Requestor-Player
