### ISSUE TITLE
Town NPCs with no given name appear as [Town NPC] the [Town NPC]

### ISSUE THREAD

**Issue by CUBEkid04** [bluemagic123/tModLoader#2605] opened 2022-06-24 01:05 UTC
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Town NPCs with no given name (such as Santa Claus) on Housing, Happiness and Chat appears as "[Town NPC] the [Town NPC]", say that for Santa Claus it would appear as "Santa Claus the Santa Claus"

It is also the same deal for a modded town NPC with no given name

### Expected Behavior

Town NPCs with no given name should be appearing as "[Town NPC]" rather than "[Town NPC] the [Town NPC]"

### Actual Behavior

Town NPCs with no given name appear as "[Town NPC] the [Town NPC]" (in chat, housing and happiness)

Santa Claus also falls under this being named "Santa Claus the Santa Claus"

**Comment by JavidPack** [comment] 2022-06-24 02:19
I think this was reported and is fixed for next release, did you search the closed issues?

**Comment by CUBEkid04** [comment] 2022-06-24 02:47
> I think this was reported and is fixed for next release, did you search the closed issues?

Yes, I looked in the closed issues

**Comment by JavidPack** [comment] 2022-06-24 10:33
duplicate of #2554

**Closed as completed by JavidPack** 2022-06-24 10:33 UTC
Labels: Bug, Requestor-Player
