### ISSUE TITLE
Custom menu theme causes multiplayer server to always start at 12:00pm

### ISSUE THREAD

**Issue by PrinceLikesCookies** [bluemagic123/tModLoader#3206] opened 2023-01-23 17:26 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I switch to a custom menu theme that's different than the ones that come with tmodloader, the time will always start from 12:00pm in multiplayer and after 12:59pm it reverts back to the actual original time.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10482141/client.log)

### Steps to reproduce

1. Switch menu theme to custom theme ( Like calamity themes)
2. Start a multiplayer world (Regular host and play) 
3. The time will be 12:00pm exactly everytime
4. After 12:59pm background will change to original time and time jumps to original time

### Expected Behavior

It should be loading up the correct time everytime even if I have a custom menu.

### Actual Behavior

The time always starts at 12:00pm in a multiplayer world and reverts to original time after 12:59

### Reproduction frequency

From what I've seen every time

### Additional Information

When I switch to a menu theme like the ones that come with tml, the time shows the actual time everytime.

**Comment by JavidPack** [comment] 2023-01-23 18:27
Can you confirm for us that this happens with only ExampleMod enabled? We need to know that this isn't a bug with other mods you have installed.

**Comment by PrinceLikesCookies** [comment] 2023-01-23 18:32
> Can you confirm for us that this happens with only ExampleMod enabled? We need to know that this isn't a bug with other mods you have installed.

I've done a bit of testing and it appears calamity is the issue, I'm not quite sure why it happens though

**Comment by steviegt6** [comment] 2023-01-23 19:13
> > Can you confirm for us that this happens with only ExampleMod enabled? We need to know that this isn't a bug with other mods you have installed.
> 
> I've done a bit of testing and it appears calamity is the issue, I'm not quite sure why it happens though

```cs
Main.time = 27000;
Main.dayTime = true;
```

We use this small snippet of code in our override of `ModMenu::PreDrawLogo` to essentially freeze time (as well as actually draw everything) as the menu looks weird at night. This there a better way to approach this? I'll forward this to the rest of the team in a bit.

I'm not at a computer to test, but my best guess is this ends up setting the time right as the world loads in. Is this reproducible in singleplayer as well? I can't think of a reason for only multiplayer to be affected.

**Comment by PrinceLikesCookies** [comment] 2023-01-23 19:32
> > > Can you confirm for us that this happens with only ExampleMod enabled? We need to know that this isn't a bug with other mods you have installed.
> > 
> > 
> > I've done a bit of testing and it appears calamity is the issue, I'm not quite sure why it happens though
> 
> ```cs
> Main.time = 27000;
> Main.dayTime = true;
> ```
> 
> We use this small snippet of code in our override of `ModMenu::PreDrawLogo` to essentially freeze time (as well as actually draw everything) as the menu looks weird at night. This there a better way to approach this? I'll forward this to the rest of the team in a bit.
> 
> I'm not at a computer to test, but my best guess is this ends up setting the time right as the world loads in. Is this reproducible in singleplayer as well? I can't think of a reason for only multiplayer to be affected.

I'm not able to reproduce it in single player. It appears to only happen in multiplayer

**Comment by Chicken-Bones** [comment] 2023-01-23 19:34
@steviegt6 It looks like `Main.SetBackColor` contains the color settings you might wish to override. You could consider an `On` hook. Alternatively, `SystemLoader.ModifySunLightColor` runs right after, so you could alter `Main.ColorOfTheSkies` there (it's even passed in)

**Comment by Chicken-Bones** [comment] 2023-01-23 19:35
Closing as a Calamity issue

**Closed as completed by Chicken-Bones** 2023-01-23 19:35 UTC
Labels: NEW ISSUE, Requestor-Player
