### ISSUE TITLE
Blue box glitch

### ISSUE THREAD

**Issue by Jawell** [bluemagic123/tModLoader#2191] opened 2022-03-08 12:04 UTC
### Version

Latest public-1.4-alpha

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I'm using "The Blessed Apple", the unicorn appear with a blue box. All mods and textures was disabled.
<img width="1904" alt="Screenshot 2022-03-08 at 13 28 14" src="https://user-images.githubusercontent.com/21054523/157230726-996f7429-94a4-49ed-bdcd-cd15e609cab3.png">
.

### Log File

<details>
  <summary>client.log</summary>
  
  ```
[13:26:39] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+0.12-1.4-Alpha-7a48944a83b4ab8b783506904589b0a31e5142fc-5249507983872647509
[13:26:39] [Main Thread/INFO] [tML]: Log date: 3/8/2022
[13:26:39] [Main Thread/INFO] [tML]: Running on OSX X64 NetCore 6.0.0
[13:26:39] [Main Thread/INFO] [tML]: Executable: ~/Library/Application Support/Steam/steamapps/common/tModLoader/tModLoader.dll
[13:26:39] [Main Thread/INFO] [tML]: Working Directory: ~/Library/Application Support/Steam/steamapps/common/tModLoader
[13:26:39] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.GetJitObject()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources() in tModLoader\Terraria\ModLoader\Core\LoggingHooks.cs:line 38
   at Terraria.ModLoader.Logging.Init(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 77
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 166
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 60
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 67

[13:26:40] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[13:26:41] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[13:26:41] [Main Thread/DEBUG] [tML]: 	attempting load ~/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/Native/OSX/libFNA3D.0.dylib
[13:26:41] [Main Thread/DEBUG] [tML]: 	success
[13:26:41] [Main Thread/INFO] [tML]: Checking Steam installation...
[13:26:41] [Main Thread/INFO] [tML]: Steam installation OK.
[13:26:41] [Main Thread/INFO] [Terraria]: Found Terraria steamapp install at: ~/Library/Application Support/Steam/steamapps/common/Terraria
[13:26:41] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 152.6 MB available
[13:26:42] [Main Thread/INFO] [FNA]: FNA3D Driver: OpenGL
[13:26:42] [Main Thread/INFO] [FNA]: OpenGL Renderer: AMD Radeon Pro 5300M OpenGL Engine
[13:26:42] [Main Thread/INFO] [FNA]: OpenGL Driver: 2.1 ATI-4.7.103
[13:26:42] [Main Thread/INFO] [FNA]: OpenGL Vendor: ATI Technologies Inc.
[13:26:42] [Main Thread/INFO] [FNA]: MojoShader Profile: glsl120
[13:26:43] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: Color LCD, DisplayMode: {{Width:1792 Height:1120 Format:Color}}, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[13:26:43] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Color LCD, DisplayMode: {{Width:1792 Height:1120 Format:Color}}, Profile: Reach, Width: 800 -> 1792, Height: 480 -> 990, Fullscreen: False, Display: \\.\DISPLAY1
[13:26:43] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null -> FAudio
[13:26:43] [Main Thread/DEBUG] [tML]: 	attempting load ~/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/Native/OSX/libFAudio.0.dylib
[13:26:43] [Main Thread/DEBUG] [tML]: 	success
[13:26:58] [.NET ThreadPool Worker/INFO] [tML]: Unloading mods
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: Finding mods...
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: Instantiating Mods...
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: Initializing: ModLoader (tModLoader) v0.12
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: Setting up...
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: Loading: ModLoader (tModLoader) v0.12
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 1,4 GB
[13:26:59] [.NET ThreadPool Worker/INFO] [tML]: Adding Recipes...
[13:27:13] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data
[13:27:14] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[13:27:14] [.NET ThreadPool Worker/INFO] [StatusText]: Loading map data
[13:27:14] [.NET ThreadPool Worker/INFO] [StatusText]: Drawing map
[13:27:14] [Main Thread/INFO] [Terraria]: Entering world with player: Chell, IsCloud=False, Size=6400x1800
[13:27:20] [.NET ThreadPool Worker/INFO] [StatusText]: Saving map data
[13:27:20] [.NET ThreadPool Worker/INFO] [StatusText]: Saving world data
[13:27:21] [.NET ThreadPool Worker/INFO] [StatusText]: Validating world save
[13:27:29] [.NET ThreadPool Worker/INFO] [Terraria]: Generating World: Serene Strait
[13:27:29] [Main Thread/INFO] [tML]: Generating world terrain...
[13:27:29] [Main Thread/INFO] [tML]: Adding sand...
[13:27:29] [Main Thread/INFO] [tML]: Generating ocean sand...
[13:27:29] [Main Thread/INFO] [tML]: Putting dirt behind dirt...
[13:27:29] [Main Thread/INFO] [tML]: Placing rocks in the dirt...
[13:27:30] [Main Thread/INFO] [tML]: Placing dirt in the rocks...
[13:27:30] [Main Thread/INFO] [tML]: Adding clay...
[13:27:30] [Main Thread/INFO] [tML]: Making random holes...
[13:27:31] [Main Thread/INFO] [tML]: Generating small caves...
[13:27:31] [Main Thread/INFO] [tML]: Generating large caves...
[13:27:31] [Main Thread/INFO] [tML]: Generating surface caves...
[13:27:31] [Main Thread/INFO] [tML]: Adding snow...
[13:27:31] [Main Thread/INFO] [tML]: Generating jungle...
[13:27:33] [Main Thread/INFO] [tML]: Adding more grass...
[13:27:34] [Main Thread/INFO] [tML]: Desertification...
[13:27:39] [Main Thread/INFO] [tML]: Generating floating islands...
[13:27:39] [Main Thread/INFO] [tML]: Adding mushroom patches...
[13:27:40] [Main Thread/INFO] [tML]: Chiseling marble...
[13:27:40] [Main Thread/INFO] [tML]: Growing granite...
[13:27:41] [Main Thread/INFO] [tML]: Placing mud in the dirt...
[13:27:41] [Main Thread/INFO] [tML]: Adding silt...
[13:27:41] [Main Thread/INFO] [tML]: Adding shinies...
[13:27:41] [Main Thread/INFO] [tML]: Creating underworld...
[13:27:42] [.NET ThreadPool Worker/INFO] [StatusText]: Creating underworld
[13:27:43] [Main Thread/INFO] [tML]: Making the world bloody...
[13:27:44] [.NET ThreadPool Worker/INFO] [StatusText]: Creating dungeon
[13:27:44] [Main Thread/INFO] [tML]: Adding water bodies...
[13:27:44] [Main Thread/INFO] [tML]: Generating mountain caves...
[13:27:44] [Main Thread/INFO] [tML]: Adding gems...
[13:27:44] [Main Thread/INFO] [tML]: Gravitating sand...
[13:27:44] [Main Thread/INFO] [tML]: Cleaning up dirt backgrounds...
[13:27:44] [Main Thread/INFO] [tML]: Placing altars...
[13:27:44] [Main Thread/INFO] [tML]: Creating jungle ruins...
[13:27:44] [Main Thread/INFO] [tML]: Creating hornet nests...
[13:27:44] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[13:27:44] [Main Thread/INFO] [tML]: Settling liquids...
[13:27:46] [Main Thread/INFO] [tML]: Smoothing the world...
[13:27:47] [Main Thread/INFO] [tML]: Creating waterfalls...
[13:27:47] [Main Thread/INFO] [tML]: Weathering caverns...
[13:27:48] [Main Thread/INFO] [tML]: Placing statues...
[13:27:48] [Main Thread/INFO] [tML]: Hiding treasure...
[13:27:48] [Main Thread/INFO] [tML]: Hiding more treasure...
[13:27:48] [Main Thread/INFO] [tML]: Growing spider caves...
[13:27:48] [Main Thread/INFO] [tML]: Mossification...
[13:27:49] [Main Thread/INFO] [tML]: Making cave walls...
[13:27:49] [Main Thread/INFO] [tML]: Growing rich mahogany...
[13:27:50] [Main Thread/INFO] [tML]: Placing breakables...
[13:27:50] [Main Thread/INFO] [tML]: Spreading grass...
[13:27:50] [Main Thread/INFO] [tML]: Placing traps...
[13:27:51] [Main Thread/INFO] [tML]: Placing objects...
[13:27:51] [Main Thread/INFO] [tML]: Planting trees...
[13:27:51] [Main Thread/INFO] [tML]: Planting herbs...
[13:27:51] [Main Thread/INFO] [tML]: Planting weeds...
[13:27:52] [Main Thread/INFO] [tML]: Growing vines...
[13:27:52] [Main Thread/INFO] [tML]: Planting flowers...
[13:27:52] [Main Thread/INFO] [tML]: Planting mushrooms...
[13:27:52] [Main Thread/INFO] [tML]: Settling liquids...
[13:27:54] [Main Thread/INFO] [tML]: Growing cacti...
[13:27:55] [Main Thread/INFO] [tML]: Clean up...
[13:27:55] [Main Thread/INFO] [tML]: Generating structures..Dead Man's Chests...
[13:27:55] [Main Thread/INFO] [tML]: Generating structures..Thin Ice...
[13:27:55] [Main Thread/INFO] [tML]: Generating structures..Campsites...
[13:27:55] [Main Thread/INFO] [tML]: Generating structures..Explosive Traps...
[13:27:55] [Main Thread/INFO] [tML]: Generating structures..Living Trees...
[13:27:55] [Main Thread/INFO] [tML]: Generating structures..Long Minecart Tracks...
[13:27:56] [Main Thread/INFO] [tML]: Generating structures..Standard Minecart Tracks...
[13:27:59] [Main Thread/INFO] [tML]: Generating structures..Lava Traps...
[13:27:59] [Main Thread/INFO] [tML]: Growing water plants...
[13:28:00] [Main Thread/INFO] [tML]: Disarming broken traps...
[13:28:00] [Main Thread/INFO] [tML]: Final clean up...
[13:28:00] [.NET ThreadPool Worker/INFO] [tML]: Generation of 6400x1800 Crimson world with seed 107193628 completed in 0m 31s 524ms
[13:28:00] [.NET ThreadPool Worker/INFO] [StatusText]: Saving world data
[13:28:01] [.NET ThreadPool Worker/INFO] [StatusText]: Validating world save
[13:28:06] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data
[13:28:06] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[13:28:07] [Main Thread/INFO] [Terraria]: Entering world with player: Chell, IsCloud=False, Size=6400x1800
[13:28:22] [.NET ThreadPool Worker/INFO] [StatusText]: Saving map data
[13:28:22] [.NET ThreadPool Worker/INFO] [StatusText]: Saving world data
[13:28:22] [.NET ThreadPool Worker/INFO] [StatusText]: Validating world save

  ```
  
</details>

[Logs.zip](https://github.com/tModLoader/tModLoader/files/8205805/Logs.zip)

### Steps to reproduce

Get "The Blessed Apple" -> Press "R" to invoke unicorn.

### Expected Behavior

Unicorn without blue box around.

### Actual Behavior

Unicorn with blue box around

### Reproduction frequency

Every time when you use "The Blessed Apple"

### Additional Information

I'm using the Steam version and selected `public-1.4-alpha` version in the Betas tab
Version in the game: `tModLoader v0.12 1.4 Alpha 7a48944a, built 3/6/2022 10:49PM`
macOs version: `macOS Monterey 12.2.1 (21D62)`
General: `16-inch, 2019`
Graphics: `AMD Radeon Pro 5300M 4 GB`
Display: `Built-in Retina Display`
This bug will appear in a clean, freshly downloaded tModLoader from Steam.

**Comment by JavidPack** [comment] 2022-03-09 00:48
Seems to be a duplicate of #2158 . Seems both reports involve Mac and Radeon graphics card

**Comment by Jawell** [comment] 2022-03-09 07:18
And duplicate of #1918

**Comment by Mirsario** [comment] 2022-03-11 14:25
Closing in favor of the first issue (#1918), though good info here.

**Closed as completed by Mirsario** 2022-03-11 14:25 UTC
Labels: Bug, Requestor-Player
