### ISSUE TITLE
Dissapearing Mobs Fix Discomfirmation

### ISSUE THREAD

**Issue by Fanmember** [bluemagic123/tModLoader#23] opened 2016-04-07 01:56 UTC
Hi! I am an user of your (awesome :D) modding thing. Anyhow, I looked on your forum page about the mod, and I saw that you had a known server bugs section. I the bug you still didn't know about if it was still working is still not fixed. I just wanted to give you a disconfirmation (not fixed), as I use the server .exe file with my two friends. I open the port, and they join. As for the bug, only some enemies disappear but others stay. I am using the Tremor mod and Thorium mod, and mobs from both mods can disappear, but some still stay. It seems like NPC's can see and still attack the invisible mobs, but summons cannot. I think I only saw it once, but I think that if a NPC hits it first, it will stay. I am not certain. I only saw it once, and it never happened as my summons kept on attacking first from then on. There was another occasion where a mob disappeared, but then it hit me (it a spot it should of been) and came back. It only happened once. I am using the current version of each mod.

Thank you for looking at this. I wish you good luck with your homework. Have a nice day! :)

**Comment by Chicken-Bones** [comment] 2016-04-07 06:02
I would like to confirm, are only modded enemies disappearing?

**Comment by Fanmember** [comment] 2016-04-07 06:24
Yes. Mobs like a phantom will not dissapeared but a radiant bat would. Everything that is in vanilla Terraria does not. Currently, it has been only mobs to my extent. Thank you

**Comment by Chicken-Bones** [comment] 2016-04-07 06:35
Thankyou for confirming this, I'm heading up the networked mod support. 
Can you provide any more information on when enemies disappear?
Is there anything you can do to make them more or less likely to disappear?
Similarly, what should I do to observe the bug in action? (because if I can observe it on my computer, I can fix it)
Does it happen less often (if at all) on a computer with zero ping (server and client on the same machine)?

**Comment by Fanmember** [comment] 2016-04-07 06:45
The only other information I can think of is that not all mobs disappear. I think it is just player damage that makes it dissapear. My friend found a sword in lava on the multiplayer server that usually drops from a mob that disappears when hit. Anyhow, you can replicate it by hosting up a server through the console and connecting to it though 127.0.0.1 on port 7777. It may take you a while to find some mobs. I think a great place to find them would probably be underground. I used the Thorium and Tremor mods. Each mod has disappearing mobs, and one forum of one of the mobs said it wasn't the mod's fault. This only happened on multiplayer, and never happened on single player. A mob I know that dissapeares is an alpha wolf that comes from the ice biome. The omega wolf doesn't dissapear. There is also a mob called the mud man in the jungle that disappears. Anyhow, it happens to all three of us, and I am the one hosting.

**Comment by Chicken-Bones** [comment] 2016-04-07 07:39
Do enemies just disappear on your screen, or are there invisible enemies that spawn (for some of you)?
Do enemies reappear when they hit you or an npc, or when hit by another player?

**Comment by Fanmember** [comment] 2016-04-07 13:26
Sorry about the big break. I went to sleep.

For the most part, they never spawn invisible. They disappear on the screen, but only rarely will they ever come back. It only came back once when it magically somehow came back and hit me. When it disappears, it doesn't reappear when it gets hit while it is invisible. What happened once is that I saw a cool enemy on our way to the jungle who was trapped in the sand, and I was like, "Hey guys, look at this!" They all did not respond, and I think that they didn't see it at all. However, I spawned in a tiki boss (rope, stingers, mahogany wood, and tissue samples/shadow scales), we all saw it spawn in. However, it disappeared for all three of us. We did not test if it disappeared at different times depending on who hit it.

**Comment by Fanmember** [comment] 2016-04-07 16:17
I would also like to note that bosses do not work at all. The boss either does not spawn or they disappear.

Thank you Chicken-Bones!

**Comment by Rahmiel** [comment] 2016-04-07 18:01
Just to update this, the mobs are still in memory according to a few posts on the forums. This is proven by hitting a mob, making it disappear, then dumping lava down and it will reappear. I have a feeling this whole issue has something to do with syncing, seeings as its multiplayer only. As for bosses I have been able to get bosses to not disappear just by continuously trying to fight them until one works. So it also seems a bit RNG on whether or not they work. It is good to see that I'm not the only one talking about this now.

**Comment by Rahmiel** [comment] 2016-04-07 18:15
To Clarify this is what I have found so far.

1. It is exclusive to modded mobs
2. The mobs disappear when hit by a player exclusively
3. The mobs do not ALWAYS disappear
4. The mobs will reappear if affected by environmental damage i.e. lava
5. This issue is seen with bosses as well, bosses successfully summon but disappear after being attacked by a player

**Comment by bluemagic123** [comment] 2016-04-07 19:44
Hm, can you guys test the Abomination in the ExampleMod and see whether that disappears for you?

**Comment by Fanmember** [comment] 2016-04-07 20:14
4 needs to be changed. They will not reappear if it is affected by environmental damage. Environmental damage stops it from disappearing usually. I will ask my friends about testing it soon

**Comment by bluemagic123** [comment] 2016-04-07 20:32
Hmm, this is so troublesome. Everyone is reporting different stuff happening. For some people (including me), NPCs don't disappear at all. Most people say they reappear after environmental damage. And now you're saying they don't reappear.

**Comment by Fanmember** [comment] 2016-04-07 20:35
I am using a console server on multiplayer. I am using Windows

**Comment by Fanmember** [comment] 2016-04-07 21:14
Also, I have not seen one reappear.

**Comment by Fanmember** [comment] 2016-04-07 23:37
Coznix, the Fallen Beholder was able to successfully spawn in and my friends and I could defeat it. It was a nether mob, and we let it live for a good 5-10 seconds before attacking it. Unlike other modded bosses, it has successfully spawned in and not disappear.

**Comment by JavidPack** [comment] 2016-04-07 23:57
Just FYI, either Tremor or Thorium had 2 versions that were released with the same version number, and it is still the current version, so you might want to confirm the file sizes with your co-players just so we can cross that off the list of things to think about.

**Comment by Rahmiel** [comment] 2016-04-08 00:33
Alright how the hell do I get the abomination to spawn in example mod, I'm trying to test this and its starting to get on my nerves.

**Comment by Fanmember** [comment] 2016-04-08 00:48
My friend and I who are using windows have the same file size, and my Mac friend has a file that is a tad bigger. When we tried spawning another boss (not in the example mod), it spawned in the corner of the map.

**Comment by Fanmember** [comment] 2016-04-08 01:12
How do you use the foul orb in the example mod?

**Comment by Rahmiel** [comment] 2016-04-08 01:16
You have to kill plantera then use it in the underworld. Anyways, first try the boss worked fine, by the way that boss is COOL AS HELL. Anyways I'm gonna do a few more tests but my assumption is it will work fine, none of the mobs in Example Mod are despawning like they do in other mods.

**Comment by Rahmiel** [comment] 2016-04-08 01:24
Confirmed my last statement, I was able to fight Abomination from ExampleMod 5/5 times no issues. So what does that tell us and how helpful is it?

**Comment by bluemagic123** [comment] 2016-04-08 01:48
The main problem was that everyone's experiences regarding this bug are all different. But if everything experiences the lack of the bug with the ExampleMod stuff, then that's one experience that's constant, which might give us something to go on (we can try to find out what exactly is different between everything, etc).

**Comment by Rahmiel** [comment] 2016-04-08 02:14
It might help to try to get people to post their experiences here in github to get all of the information in one place. I've been trying to pick through the forums, but there is just so much stuff going on there.

**Comment by Rahmiel** [comment] 2016-04-08 02:28
I'm noticing something really weird that may help pinpoint the issue. Some modded mobs don't despawn like the others do. An example of this is the Zombie Knight in Tremor. I have a tiny theory, but I don't know enough about code to confirm it, but I feel that the Zombie Knight is just a retextured Zombie while the other mobs that disappear have majorly different AI patterns. Again I could just be talking out of my pie hole but it seems interesting that the Zombie Knight is stable when most of the more customized mobs aren't.

**Comment by Fanmember** [comment] 2016-04-08 02:44
I think you might be right, but how would that explain the abomination. Does he have a different ai? Anyhow, my friend had to use three of the Abomination spawners to get one to spawn, but I didn't have that problem when I tried. I was the host and he was not. He was also on Mac, and he had to get my example .tmod. Also, the buckethead zombie disappeared as well.

**Comment by Fanmember** [comment] 2016-04-08 02:45
Also, the abomination does not disappear

**Comment by Rahmiel** [comment] 2016-04-08 03:20
Yeah the abomination not spawning for your friend is weird. According to blue that is what is throwing off this whole thing is that everyone is having completely different experiences. It is good that once it spawns the boss doesn't disappear. So far we have confirmed that Abomination is 100% working in that aspect which could be helpful for pinpointing the issue. Honestly though, this seems like a combination of so many issues manifesting as one big issue, and that is a problem.

**Comment by Fanmember** [comment] 2016-04-08 14:41
Maybe the issue could be some specific things used in the Tremor mod and the Thorium mod that is not included in the example mod?

**Comment by Rahmiel** [comment] 2016-04-08 18:51
There are other mods doing it too, so its something that EVERYONE except ExampleMod are doing with their mobs.

**Comment by bluemagic123** [comment] 2016-04-08 21:36
In the other mods, it's only some types of enemies that disappear, right? And if I remember correctly, in Tremor, people have said the Alpha Wolves disappear while the other ones don't; even though they should be same. I'm kind of worried this problem might be affecting random monsters.

**Comment by Fanmember** [comment] 2016-04-08 21:42
You are correct. Alpha Wolves disappear while Omega Wolves do not. I think Beta Wolves might.

**Comment by Rahmiel** [comment] 2016-04-09 00:10
In my experience I would have to say its not 100% random, some mobs are completely immune. Some mobs do sometimes and don't others, and some mobs do it pretty much every time. I think the interesting part is the fact that people have been able to get them to reappear using environmental damage. I can say that it is NOT happening with any mobs in ExampleMod for me at least.

**Comment by Fanmember** [comment] 2016-04-09 01:35
I completely agree with Rahmiel; everything I did matches up with him.

**Comment by Fanmember** [comment] 2016-04-10 02:51
Any updates about figuring out what the problem is?

**Comment by Rahmiel** [comment] 2016-04-10 16:38
The problem has to be with the way the mods are writing their mobs. However finding the issue is like looking for a needle in a haystack. It is going to be a while fan, possibly a long while, the only thing we can do is wait and hope Blue or Chicken-Bones figures it out.

**Comment by CursedEmber** [comment] 2016-05-15 17:13
Hi, sorry for replaying to this post late but my friends and I are also having the same issue on our server when the modded mobs are disappearing when they get hit. Has this issue been fixed or is it still being worked on ?

**Comment by max100e** [comment] 2016-05-30 12:52
Is this still being worked on? I can proof its still not fixed.

**Comment by Zenn123** [comment] 2016-05-30 13:59
Now mobs dissapearing only in expert mode

**Comment by bluemagic123** [comment] 2016-05-30 18:58
Hm, I wonder if that's why none of us have been able to duplicate it. I'll get straight to testing that once the Mac/Linux versions are complete.

**Closed** 2016-05-31 01:06 UTC
