### ISSUE TITLE
When riding mounts or minecarts they will have a golden box around them(

### ISSUE THREAD

**Issue by mxt828** [bluemagic123/tModLoader#2426] opened 2022-05-24 17:49 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I'm on the steam deck if that matters

**Comment by JavidPack** [comment] 2022-05-24 19:18
duplicate of #1918 , we'll track the issue there

**Closed as completed by JavidPack** 2022-05-24 19:18 UTC
Labels: Bug, Requestor-Player
