### ISSUE TITLE
Monomod uname complication prevents Linux X86_64 detection

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3766] opened 2023-08-27 13:41 UTC
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

this is ISNT on my steam deck, but on my linux PC

it crashes when i try to start (i start via `start-tModLoader.sh`)
and i tried to reinstall TML, but its still broken...

### Log File

Well again... github...
https://drive.google.com/file/d/1zq6D7OCy3fR8lsYnSt3P6-8v5iUwUOTg/view?usp=sharing

### Steps to reproduce

1. Try to start
2. Crash

### Expected Behavior

Work

### Actual Behavior

Crash

### Reproduction frequency

100%

### Additional Information

This is not working out well for me... Three different crashes...

**Comment by JavidPack** [comment] 2023-08-29 17:59
First, try deleting the dotnet folder in the install directory, then make sure there is no proton involved. (I didn't see any, but just make sure)

@Chicken-Bones it looks like Monomod isn't detecting this system as x86_64 for some reason (client.log), do you have a clue what's going on?

```
[15:31:59.602] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2023.06.25.31|2023.06|stable|Stable|1cf5af1a24a961fcbe0d1d7fc31dcda160496504|5249959922336091465 built 8/12/2023 12:39AM
[15:31:59.610] [Main Thread/INFO] [tML]: Log date: 8/27/2023
[15:31:59.610] [Main Thread/INFO] [tML]: Running on Linux (v6.4.11.2) X64 NetCore 6.0.0
[15:31:59.610] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[15:31:59.610] [Main Thread/INFO] [tML]: Executable: /home/kaktus/Games/Heroic/Terraria/game/tModLoader/tModLoader.dll
[15:31:59.610] [Main Thread/INFO] [tML]: Working Directory: /home/kaktus/Games/Heroic/Terraria/game/tModLoader
[15:31:59.652] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 83
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 116
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in /_/src/MonoMod.Utils/Helpers.cs:line 167
   at MonoMod.Core.Platforms.PlatformTriple.get_Current() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 113
   at MonoMod.Core.DetourFactory.CreateDefaultFactory() in /_/src/MonoMod.Core/IDetourFactory.cs:line 80
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in /_/src/MonoMod.Utils/Helpers.cs:line 158
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in /_/src/MonoMod.RuntimeDetour/DetourContext.cs:line 103
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 409
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 377
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 319
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 17
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 93
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 211
   at Terraria.MonoLaunch.Main_End(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 71
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 57
   at Terraria.MonoLaunch.Main(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 64

[15:31:59.653] [Main Thread/FATAL] [tML]: An unexpected error occured during tML startup

System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.Systems.LinuxSystem..ctor() in /_/src/MonoMod.Core/Platforms/Systems/LinuxSystem.cs:line 47
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 83
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 116
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in /_/src/MonoMod.Utils/Helpers.cs:line 167
   at MonoMod.Core.Platforms.PlatformTriple.get_Current() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 113
   at MonoMod.Core.DetourFactory.CreateDefaultFactory() in /_/src/MonoMod.Core/IDetourFactory.cs:line 80
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in /_/src/MonoMod.Utils/Helpers.cs:line 158
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in /_/src/MonoMod.RuntimeDetour/DetourContext.cs:line 103
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 409
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 377
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 319
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 17
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 93
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284
```

**Comment by ghost** [comment] 2023-08-30 21:54
i already tried to delete the dotnet folder (i even tried to reinstall the whole tML folder), didn't fix it, and i started it via the `sh` in the file browser not on steam, so its probably not proton (it also said "Running on Linux" so yeah, most likely not)

**Comment by ghost** [comment] 2023-08-30 22:03
~~HEY, just wanted to tell you that the issue doesn't happen the the latest pre-release!
Now the game starts fine!~~

(oh forgot, this is version 1.0.3, the latest pre-relase, so the issue still remains...)
the latest 1.4.4 pre-release still crashes

WINE makes the game work (but thats ofc not has steam installed so no browser and not native...)

also side question, why is there no more linux and mac "binary" since 1.4?

**Comment by JavidPack** [comment] 2023-08-30 23:44
With 1.4 we moved to .net core, and as such can launch the game directly through dotnet without a mono wrapper. Basically all OS are now more consistent with each other so that we can work more efficiently and so that we and modders can use newer .net features.

In 1.3, the disconnect between linux and windows increased the amount of work managing how things work and are distributed, now it's all the same release.

**Comment by Elvyria** [comment] 2023-10-31 11:00
Was never able to play 1.4.4 and finally got enough of this error, so i looked some stuff up.
This happens because MonoMod is trying to get results from [libc::uname](https://man7.org/linux/man-pages/man2/uname.2.html) in a VERY VERY BAD WAY.
Instead of accessing `utsname` struct field it just does this:

`MonoMod.Utils.PlatformDetection.cs`
```cs
private static (OSKind OS, ArchitectureKind Arch) DetectPlatformInfo() {
...
  var kernelName = GetCString(buffer, out var nullByteOffs).ToUpperInvariant();
  buffer = buffer.Slice(nullByteOffs);
  
  for (var i = 0; i < 4; i++) { // we want to jump to string 4, but we've already skipped the text of the first
      if (i != 0) {
          // skip a string
          nullByteOffs = buffer.IndexOf((byte)0);
          buffer = buffer.Slice(nullByteOffs);
      }
      // then advance to the next one
      var j = 0;
      for (; j < buffer.Length && buffer[j] == 0; j++) { }
      buffer = buffer.Slice(j);
  }

  // and here we find the machine field
  var machineName = GetCString(buffer, out _).ToUpperInvariant();
...
}
```
Yeah, and you guessed it, it jumps on the wrong field.
So, a couple `dll` patches later, i found that on my system, it gets `version` field and it just fails to find `X86_64` or `AMD64` in it. (which is a weird way to check for the architecture anyways)

So, the quick and dirty way of bypassing this is hooking up to [libc::uname](https://man7.org/linux/man-pages/man2/uname.2.html) and faking the needed field ourselves. 
Made it for myself, but published it with details in case someone wants to try it out - [monomod-uname-hack](https://github.com/Elvyria/monomod-uname-hack) .

This is not a tModLoader issue. Finally can play the game again.

**Comment by Chicken-Bones** [comment] 2023-11-07 05:31
@Elvyria can you provide your system, and the sample output given from `uname`?

**Comment by Elvyria** [comment] 2023-11-07 15:52
Distro: `Void Linux`
Architecture: `x86-64`
GLibc: `2.36`
tModLoader: `v2023.9.3.4 (Steam Native)`

Here's what `libc::uname` returns:
```
utsname {
    sysname: Linux
    nodename: oni
    release: 6.5.10_1
    version: #1 SMP PREEMPT_DYNAMIC Sat Nov  4 08:57:12 UTC 2023
    machine: x86_64
    domainname: (none)
}
```

**Comment by Chicken-Bones** [comment] 2023-11-08 00:30
In your comment you state that MonoMod is finding the `version` field. This seems unlikely. Instead, I believe the fault to be with `machineName.Contains("X86_64", StringComparison.Ordinal)` which does a case sensitive comparison and therefore does not detect `x86_64`. Can you confirm this? 

One way to do so would be to enable monomod logging (`export MONOMOD_LogToFile=mmlog.txt`) and look for the output from
```cs
MMDbgLog.Trace($"uname() call returned {kernelName} {machineName}");
```

**Comment by Elvyria** [comment] 2023-11-08 06:21
Nope, that was my assumption at first as well, but it does toUpperCase beforehand.
Why would you say that it's unlikely? Who can guarantee that compiler doesn't reorder fields as it pleases?
(which it does, at least in Rust, for memory packing / alignment)
```
165: var machineName = GetCString(buffer, out _).ToUpperInvariant();
```

**Comment by Elvyria** [comment] 2023-11-08 07:20
Let's make it really simple, here's some C.
```c
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/utsname.h>

int main(int argc, char *argv[])
{
    struct utsname buffer;
    errno = 0;
    if (uname(&buffer) < 0) {
        return EXIT_FAILURE;
    }
    
    for(int i = 0; i < sizeof(buffer); i++) {
        printf("%x ",((uint8_t*)&buffer)[i]);
    }
    
    return EXIT_SUCCESS;
}
```

Here's what I'm getting. (Assuming that it only contains null terminated strings)
```
4c 69 6e 75 78 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
6f 6e 69 0
65 29 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
36 2e 35 2e 31 30 5f 31 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
23 31 20 53 4d 50 20 50 52 45 45 4d 50 54 5f 44 59 4e 41 4d 49 43 20 53 61 74 20 4e 6f 76 20 20 34 20 30 38 3a 35 37 3a 31 32 20 55 54 43 20 32 30 32 33 0 0 0 0 0 0 0 0 0 0 0 0 0 0
78 38 36 5f 36 34 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
28 6e 6f 6e 65 29 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by Chicken-Bones** [comment] 2023-11-08 20:41
Ah I see. It's not reordering, it's some garbage in the `nodename` string. `oni\0e)`

**Comment by Elvyria** [comment] 2023-11-08 21:03
Yeah, but it doesn't make it into the field itself, if library actually used properly.
```c
int main(int argc, char *argv[])
{
    struct utsname buffer;
    errno = 0;
    if (uname(&buffer) < 0) {
        return EXIT_FAILURE;
    }
    
    printf("system name = %s\n", buffer.sysname);
    printf("node name   = %s\n", buffer.nodename);
    printf("release     = %s\n", buffer.release);
    printf("version     = %s\n", buffer.version);
    printf("machine     = %s\n", buffer.machine);
    
    #ifdef _GNU_SOURCE
        printf("domain name = %s\n", buffer.domainname);
    #endif
    
    return EXIT_SUCCESS;
}
```
Results in a:
```
system name = Linux
node name   = oni
release     = 6.5.10_1
version     = #1 SMP PREEMPT_DYNAMIC Sat Nov  4 08:57:12 UTC 2023
machine     = x86_64
```
So this is probably an implementation detail (part of an address, offset or size), because without the proper offset, parsing it the same way like MonoMod does, would result in a mess we have right now.

**Comment by Windows10CE** [comment] 2023-11-08 21:05
> Who can guarantee that compiler doesn't reorder fields as it pleases? (which it does, at least in Rust, for memory packing / alignment)

The C standard, which is the language the struct is defined in: https://en.cppreference.com/w/c/language/struct
> Within a struct object, addresses of its elements (and the addresses of the bit-field allocation units) increase in order in which the members were defined.

That is how Rust's `#[repr(C)]` can even exist: https://doc.rust-lang.org/nomicon/other-reprs.html#reprc

**Comment by Windows10CE** [comment] 2023-11-08 21:14
And looking at the definition on my machine, there should be no padding there. Something has placed an extra null byte in-between data inside the field itself, or our definitions for this struct are different somehow. (All of these lengths are 65 on my Arch system)
```c
struct utsname
  {
    /* Name of the implementation of the operating system.  */
    char sysname[_UTSNAME_SYSNAME_LENGTH];

    /* Name of this node on the network.  */
    char nodename[_UTSNAME_NODENAME_LENGTH];

    /* Current release level of this implementation.  */
    char release[_UTSNAME_RELEASE_LENGTH];
    /* Current version level of this release.  */
    char version[_UTSNAME_VERSION_LENGTH];

    /* Name of the hardware type the system is running on.  */
    char machine[_UTSNAME_MACHINE_LENGTH];

#if _UTSNAME_DOMAIN_LENGTH - 0
    /* Name of the domain of this node on the network.  */
# ifdef __USE_GNU
    char domainname[_UTSNAME_DOMAIN_LENGTH];
# else
    char __domainname[_UTSNAME_DOMAIN_LENGTH];
# endif
#endif
  };
```

**Comment by nike4613** [comment] 2023-11-08 21:15
Unfortunately, I *can't* just use the offsets. The offsets are platform-specific. I have observed platforms with each of the following field sizes: 129, 257, 513. [Oh, and glibc 2.35 apparently defines the length of each field as 1024.](https://elixir.bootlin.com/glibc/glibc-2.38.9000/source/bits/utsname.h#L24)

I also can't load a native binary, because I need to know which platform I'm on to load the right one, and the whole point of the `uname` call is to find that out!

**Comment by Elvyria** [comment] 2023-11-08 22:29
So, i figured what that "garbage" is - these a leftovers of the string `(none)`, which would be the `hostname` that Linux kernel itself sets [by default](https://github.com/torvalds/linux/blob/6bc986ab839c844e78a2333a02e55f02c9e57935/init/Kconfig#L363) (i guess).
So any hostname with less than (5 chars + nul) will have leftover bytes after nul.
Calling `hostname` command actually cleans it up, but it doesn't persist after reboot.

This is pretty silly.

**Comment by nike4613** [comment] 2023-11-09 09:05
What distro are you running? Also, are you setting the `hostname` kernel command line option during boot?

I've been trying to reproduce this, and so far, having tried fresh installs of both Ubuntu 22.04 (kernel version 5.15.0-27) and Arch (kernel version 6.6.1-arch1-1), short hostnames work as expected.

**Comment by Elvyria** [comment] 2023-11-09 11:46
`Void Linux`, the hostname is set during init process inside `/etc/runit/core-services/05-misc.sh` as: 
```sh
[ -r /etc/hostname ] && read -r HOSTNAME < /etc/hostname
if [ -n "$HOSTNAME" ]; then
    msg "Setting up hostname to '${HOSTNAME}'..."
    printf "%s" "$HOSTNAME" > /proc/sys/kernel/hostname
else
    msg_warn "Didn't setup a hostname!"
fi
```
Which actually is not wrong, because it follows the official? [Linux administration guidelines](https://www.kernel.org/doc/html/v6.6/admin-guide/sysctl/kernel.html#domainname-hostname), that say that running `hostname` and writing it inside `/proc/sys/kernel/hostname` should be the same (and from a regular user point it is).
Is this a kernel bug at this point?

**Comment by nike4613** [comment] 2023-11-09 20:34
Possibly. I'm going to see if I can repro on a fresh installation of Void before deciding on that.

**Comment by nike4613** [comment] 2023-11-09 20:39
Are you using musl or glibc as your libc?

**Comment by Elvyria** [comment] 2023-11-09 20:57
GLibc: `2.36`

**Comment by Elvyria** [comment] 2023-11-09 21:00
I think you could just nuke the `/etc/hostname` on any distro, reboot and then `printf any > /proc/sys/kernel/hostname`.
This should be enough to reproduce.

**Comment by JavidPack** [comment] 2023-11-30 18:45
@mr-sihc did you ever figure this out, or did you give up? From the discussion here, it seems like something strange is happening on your end that monomod can't anticipate. Just wondering if this issue needs to be opened on the Monomod repo for more work or discussion.

**Comment by nike4613** [comment] 2023-11-30 22:09
It is what @Elvyria talked about. If you nuke `/etc/hostname` and just write a short name to `/proc/sys/kernel/hostname`, it'll leave the rest of that field filled with garbage.

![image](https://github.com/tModLoader/tModLoader/assets/10411129/f2e0828d-569a-473a-a4ca-0782d75c2c08)
This was on a fresh, minimal Arch install, with `/etc/hostname` deleted. I still want to figure out why `/etc/hostname` doesn't have this problem (probably something to do with how systemd sets the hostname during boot?)

One idea I did have was to use the heuristic that each field definitely takes up at least ~32 bytes, and only scan for null bytes after that point in the same way I currently am. Unfortunately. that screenshot shows the problem with that approach... A sufficiently mangled hostname could easily break that. (I actually noticed that after nuking `/etc/hostname` it was defaulting to a network-derived hostname, including domain suffix, which in my case, is pretty close to that 32 byte length... A system that boots in that configuration then sets the hostname by writing to `/proc/sys/kernel/hostname` could very easily cause the situation I'm describing.)

Another possible solution is to try and scan backwards from the end, but that has the problem of what happens when a libc or kernel version adds more fields? `glibc` I know adds an extra field at the end, so unless I can reliably determine how many fields there should be, that won't work either...

**Comment by Elvyria** [comment] 2023-12-01 00:51
@nike4613 May i recommend a different approach? Try [getauxval(AT_PLATFORM)](https://www.man7.org/linux/man-pages/man3/getauxval.3.html) instead, which returns pointer straight to architecture string and as a bonus you can get rid of that unsound field counting code.

**Comment by Windows10CE** [comment] 2023-12-01 01:01
`getauxval` is a glibc extension, and therefore isn't portable, so it doesn't completely solve the issue.

**Comment by Elvyria** [comment] 2023-12-01 01:08
@Windows10CE I have no idea where you got that information, and since you didn't link anything, I'll assume that you're confused.

https://github.com/esmil/musl/blob/master/src/misc/getauxval.c
https://www.unix.com/man-page/freebsd/3/getauxval/

**Comment by Windows10CE** [comment] 2023-12-01 01:10
From the unix.com link you sent (and I got the information from my own manpage on getauxval, which says the same thing):
```
CONFORMING TO

       This function is a nonstandard glibc extension.
```

**Comment by nike4613** [comment] 2023-12-01 01:40
That manpage does point at the Linux procfs `/proc/pid/auxv` which contains all the same data. Unfortunately, FreeBSD does not expose that information in a similar way. (In fact, according to the FreeBSD manual, the procfs is entirely deprecated anyway, in favor of `kvm` and `libprocstat`, the latter of which exposes `procstat_getauxv`. Oh, how I wish `libprocstat` was on Linux. `procstat_getvmmap` my beloved.)

**Comment by nike4613** [comment] 2023-12-06 05:51
Example sequence that would break all previously proposed portable solutions (including the current implementation):

![image](https://github.com/tModLoader/tModLoader/assets/10411129/68d894b7-4511-4a17-b213-e642e02d5761)

It does occur to me that we could use the first field from `uname()` to determine which kernel we're on, then dispatch to kernel-specific (and non-portable) implementations to get the rest of the information we need. For instance, on Linux kernels we could use the procfs to determine architecture (if it's exposed there?), while on FreeBSD and Darwin we can use whatever other syscalls are available (for instance, `procstat_getauxval`) to gather the right information. (We should also probably get around to testing MonoMod on FreeBSD proper at some point, but there aren't any Microsoft builds of .NET targeting it, so meh?)

**Comment by ghost** [comment] 2023-12-27 16:33
> @mr-sihc did you ever figure this out, or did you give up? From the discussion here, it seems like something strange is happening on your end that monomod can't anticipate. Just wondering if this issue needs to be opened on the Monomod repo for more work or discussion.

I dont know monomod or anything dotnet so i dont really try anything
but i install my terraria like alwayds so there soudl be no error

And i'm on Artix Linux (Arch Based)


~~Can we have a force switch like `-arch x86_64` or something to force it to work for the time beeing?~~
dont need that just the `sudo hostname $(hostname)`

**Comment by DissolveDZN** [comment] 2023-12-27 17:08
have you tried **_macOS_** yet?? i'ov'e heard it's good.
GNU/Linux is what my grandpa **_used_**

**Comment by ghost** [comment] 2024-01-04 11:02
> @mr-sihc did you ever figure this out, or did you give up? From the discussion here, it seems like something strange is happening on your end that monomod can't anticipate. Just wondering if this issue needs to be opened on the Monomod repo for more work or discussion.

@JavidPack 


The problem may be that there are a lot of fields before the ARCH field, like date, and those change on system localisation

so it jumps 3 fields, usually on english system date and time would have 3 spaces there for example and other language 4, and so it _thinks_ its past the date and time, but this is only _sometimes_ true (and there may also be other factors than just date and time, like kernel version etc...)


I DID find a potential solution, this C function, which returns a struct, containing the architexture

https://man.archlinux.org/man/uname.2.en

aswell that it was standardized in 2008

I saw above that this function was talked about already, BUT they were doing it wrong

instead of hardcoding offsets, the page recommends just using a `sizeof()` to see at runtime how big the system has each member of the struct (that works because its static allocated char array)


.

oh and if all else fails, you still got `uname -m` which returns on my system: `x86_64`... yea... why did noone try this?!?!
there, youd just get the output...
this should be easy and portable! (nothing i seen  says it's not portable!)

**Comment by ghost** [comment] 2024-01-04 12:13
oh and @nike4613 might look at my suggestions as well


and yes, once my suggestions have been tried/looked at and are wrong, we should move this issue to monomod, otherwise when we fixed it with my suggestion, then we can just close it

**Comment by nike4613** [comment] 2024-01-04 12:41
This is already fixed in [the MonoMod repo](https://github.com/MonoMod/MonoMod/commit/7b2dd42e7fe13420a9bf6abbd827c82881c52b1b). No release with it just yet, I want to fix a couple other things before that.

**Comment by ghost** [comment] 2024-01-04 13:13
> This is already fixed in [the MonoMod repo](https://github.com/MonoMod/MonoMod/commit/7b2dd42e7fe13420a9bf6abbd827c82881c52b1b). No release with it just yet, I want to fix a couple other things before that.

nice! When tmodloder updates with a fixed version of monomod we can close this.

**Comment by nike4613** [comment] 2024-01-08 05:24
Uploaded RuntimeDetour 25.1.0-prerelease.2, with a fix for this.

**Closed as completed** 2024-01-09 06:34 UTC
Labels: Requestor-Player
