### ISSUE TITLE
Unplugging headphones crashes tmodloader 

### ISSUE THREAD

**Issue by Tetriscat66** [bluemagic123/tModLoader#4350] opened 2024-08-19 02:21 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Unplugging headphones from my laptop causes tmodloader to crash. 

### Steps to reproduce

1. Launch tmodloader with headphones plugged in 
2. Unplug headphones at any point (tested during mod load and on title screen) 

### Expected Behavior

Game should not crash 

### Actual Behavior

Game is crashing 

### Reproduction frequency

100% of the time 

### Additional Information

I’ve had a similar problem before where unplugging an hdmi cord from my laptop while tmodloader is running crashes it, but I don’t know if it has been fixed and am unable to test that right now.

**Comment by direwolf420** [comment] 2024-08-19 12:29
Duplicate of #2815, see CB's reply

**Closed as not planned** 2024-08-19 12:45 UTC
Labels: NEW ISSUE, Requestor-Player
