### ISSUE TITLE
Question about secret seed 05162020 world dungeon generation.

### ISSUE THREAD

**Issue by Rebuild-of-Evangelion** [bluemagic123/tModLoader#2501] opened 2022-06-05 13:13 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When creating a world with the secret seed 05162020, the generated dungeon is often deeper than the vanilla game of 05162020 seed, which leads to the Dungeon Guardian being generated immediately when the player tries to enter the dungeon. This problem will affect the progress of the game to a certain extent.

### Log File

![image](https://user-images.githubusercontent.com/62316417/172052075-a6e6e208-6965-41d8-8f0d-f4b38a321149.png)

### Steps to reproduce

1. First create the world with the secret seed 05162020 in tModLoader.
2. Enter the entrance to the dungeon (leave the world tree completely or stand on the last level platform).

### Expected Behavior

Just like the vanilla version, nothing will happen.

### Actual Behavior

Dungeon Guardian rushed out and killed the player.

### Reproduction frequency

Always.

**Comment by JavidPack** [comment] 2022-09-19 19:31
Duplicate of #2354

**Closed as not planned by JavidPack** 2022-09-19 19:31 UTC
Labels: Bug, Requestor-Player, Benefit - Low, Complexity - High
