### ISSUE TITLE
[1.4] Crimson altars cannot be broken

### ISSUE THREAD

**Issue by Pivasik22** [bluemagic123/tModLoader#2424] opened 2022-05-24 09:46 UTC
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Hello, we've found a bug in tModLoader v2022.5.92.0, we can't break crimson altars with holy hammer and others. The error is in tModLoader, we tried to disable all modifications, but the problem did not go away.

### Steps to reproduce

1. Take the Pwn hammer.
3. approach the altar in crimson.
3. hit the altar with a hammer, but it will not break because of the Bug.

### Expected Behavior

The altar in crimson should break and ore should appear.

### Actual Behavior

The altar is not broken.

### Reproduction frequency

Every time I break the altar.

**Comment by Mirsario** [comment] 2022-05-25 16:23
(https://translate.google.com)

Were you experiencing a crash, the player being hurt for hitting the altar, or what exactly?
I have now merged a fix for many sound engine related issues that could be tied to this, and though I didn't reproduce the issue prior to it, I would like to ask you to check whether or not the issue is now gone (on latest 1.4-preview.)

**Comment by JavidPack** [comment] 2022-09-14 22:59
Works for me.

**Closed as not planned by JavidPack** 2022-09-14 22:59 UTC
Labels: Bug, Requestor-Player
