### ISSUE TITLE
ModBrowser Unsupported For OSx Users

### ISSUE THREAD

**Issue by VacuumSpace** [bluemagic123/tModLoader#22] opened 2016-03-06 00:48 UTC
So, i found tModLoader a couple of days ago and i found that the ModBrowser does not seem to work for osx users. I know this is a osx issue because other users seem to have the ModBrowser work for them. Is this a client side issue (As in I did something wrong)" or is it for all Osx users. If so, is there a fix?

**Comment by JavidPack** [comment] 2016-03-06 07:54
It's nothing you've done. We know about the issue, but don't know yet why it is happening or how to fix it.

**Comment by gamrguy** [comment] 2016-05-17 19:34
From what I can tell, the ModBrowser doesn't work on my OSX either. Actually, since it's a beta, I was under the influence that it didn't work at all. Interesting.

**Comment by gamrguy** [comment] 2017-04-08 05:26
Confirmed workaround for Mod Browser not working on OSX: Enter the installation directory (`Library/Application Support/Steam/steamapps/common/Terraria/Terraria.app/Content/MacOS`) and go to `mono/config`. Open it in a text editor and change all `.so.X` file extensions to `.dylib` instead (leave plain `.so` untouched).

Suggestion: Include a modified `mono/config` file with the OSX distribution.

**Comment by JavidPack** [comment] 2017-04-11 02:20
Fixed as of 0.9.2.3

**Closed by JavidPack** 2017-04-11 02:20 UTC
Labels: Cross Platform Deficiency
