### ISSUE TITLE
"Wall is Missing" When all walls placed

### ISSUE THREAD

**Issue by KiliIsACoolName** [bluemagic123/tModLoader#3267] opened 2023-02-24 20:03 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I am playing with Calamity, and while I was trying to make a room.
![Screenshot 2023-02-24 110302](https://user-images.githubusercontent.com/126288020/221279128-ce662379-a737-416b-b127-c3ad26087750.png)

### Steps to reproduce

I'm not sure how.

### Expected Behavior

The room becomes viable.

### Actual Behavior

Description

**Comment by KiliIsACoolName** [comment] 2023-02-24 20:04
I just realized there's a typo,. I was trying to say that it says walls are missing as the title suggests.

**Comment by JavidPack** [comment] 2023-03-01 00:04
Did you try this in Terraria? This looks like a support issue, not a bug. If this works in Terraria but not tModLoader, let us know, otherwise I'll be closing this issue soon.

**Closed as not planned** 2023-03-09 18:26 UTC
Labels: NEW ISSUE, Requestor-Player
