### ISSUE TITLE
Main engine crash

### ISSUE THREAD

**Issue by THNDRMKR** [bluemagic123/tModLoader#3458] opened 2023-05-06 17:38 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

me

### Description

Does not work

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11413000/client.log)
![изображение](https://user-images.githubusercontent.com/58326841/236638901-3f805f81-2cbb-4939-8005-6c67726551da.png)

### Steps to reproduce

1. Open tmod 
2. Day ruined

### Expected Behavior

it supposed to work i guess

### Actual Behavior

X_X

**Comment by JavidPack** [comment] 2023-05-06 22:43
Duplicate of https://github.com/tModLoader/tModLoader/issues/3456, please post there.

**Closed as not planned by JavidPack** 2023-05-06 22:43 UTC
Labels: Requestor-Modders, NEW ISSUE
