### ISSUE TITLE
Please ensure Steam is logged in and running

### ISSUE THREAD

**Issue by Kami935** [bluemagic123/tModLoader#3547] opened 2023-06-14 04:27 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to open the app it causes a fatal error saying I dont have Steam running but Im logged in and running. I used the manual instalation

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11741579/client.log)

### Steps to reproduce

1. Open start-tModLoader
2. Tries to run
3. Fatal error

### Reproduction frequency

100% of the time

### Additional Information

Manual instalation was done "side-by-side" as per the guide instructions

**Comment by JavidPack** [comment] 2023-06-14 06:39
Is there a reason you used the manual install? The manual install is not intended for normal users, just gog users and possibly family share issues.

Try with the normal install. If you pirated the game, by the way, just go ahead and close this issue.

**Comment by Kami935** [comment] 2023-06-14 15:29
Hello, I used manual install because my main steam account where I have Terraria is blocked so I cant add new games or use family share. So if I have steam Terraria I cant use the manual install?

**Comment by JavidPack** [comment] 2023-06-14 17:40
Well, if your main account is disabled and you are using an account that doesn't actually have access to Terraria, then steam would see that you are basically pirating the game. Steam won't authenticate that you own the game if you don't, so the game won't launch. Manual install won't bypass the check that you actually own the game.

I'm not really sure what to suggest, aside from trying to contact steam to recover your account.

**Comment by getCursorsExe** [comment] 2023-06-24 07:04
> Try with the normal install. If you pirated the game, by the way, just go ahead and close this issue.

Do not allow Kami935 to open any more issues + lock this thread immediately.

**Comment by JavidPack** [comment] 2023-06-27 22:33
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.

**Closed as not planned by JavidPack** 2023-06-27 22:33 UTC
Labels: NEW ISSUE, Requestor-Player

**Comment by yucheen** [comment] 2024-12-12 23:30
That's because the Windows Security Center deleted some files.
