### ISSUE TITLE
NetworkText trying to cast before LocalizedText pluralization is done

### ISSUE THREAD

**Issue by Nefos1516** [bluemagic123/tModLoader#4265] opened 2024-06-14 17:15 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When trying to use `Terraria.Chat.ChatHelper.BroadcastChatMessage` to show a message from a server and passing to it a `LocalizedText` with formatting when pluralization is in play, when trying to make it a NetworkText `System.InvalidCastException: Unable to cast object of type 'Terraria.Localization.NetworkText' to type 'System.IConvertible'.` pops out and no message is shown in the chat. When trying to use a `string` it works, but `LocalizedText` doesn't

### Log File

[client.log](https://github.com/user-attachments/files/15841338/client.log)

### Steps to reproduce

1.  Use stable versions of tML
2. Write a line in localization file that goes something like `yap yap {0} {^0:yap;yaps}`
3. *I wrote it in derivative from Subworld in Update, but ModSystem.PostUpdateEverything should be fine too.* In the mod write lines that goes something like this ```if (Main.netMode == NetmodeID.Server)
{
    LocalizedText chatMessage = this.GetLocalization("your_key").WithFormatArgs(your_int);
    Terraria.Chat.ChatHelper.BroadcastChatMessage(NetworkText.From(chatMessage), Color.Teal);
}``` 
5. Launch tML in server mode

### Expected Behavior

Chat message should go through and display a localized text

### Actual Behavior

Chat message will go through, but won't display anything

### Reproduction frequency

Everytime

**Comment by JavidPack** [comment] 2024-06-17 21:31
Personal notes: 
The issue is substitution objects are converted to NetworkText via NetworkText.From/FromLiteral when sent. On the receiving end, they are still NetworkText when they are attempted to be displayed to the user, which causes `Convert.ToInt32` to error. 

The fix for this changes ApplyPluralization to just ToString the object prior to Convert.ToInt32. An alternate approach is to change NetworkText.ToString:
```diff
case Mode.LocalizationKey: {
	string text = _text;
	object[] substitutions = _substitutions;
+	substitutions = substitutions.Select(x => x is NetworkText { _mode: Mode.Literal } ? x.ToString() : x).ToArray();
	return Language.GetTextValue(text, substitutions);
}
```
I went with putting the code in `ApplyPluralization` because that can help support more scenarios, such as making `WithFormatArgs` more flexible. The other approach could potentially be more consistent in how the data is represented on client/server, but either approach works as far as I can see.

**Closed as completed** 2024-06-17 21:31 UTC
Labels: Requestor-Modders

**Comment by JavidPack** [comment] 2024-06-17 21:33
There is no easy workaround I can think of at this time, we'll try to fast track this fix if possible. One workaround is to just send the text results of LocalizedText.Value directly in the meantime. This will mean that the message is not localized for clients, but it's better than crashing until it is fixed.
