### ISSUE TITLE
[1.4] Some Dyes Acting Strange

### ISSUE THREAD

**Issue by Antirhinnum** [bluemagic123/tModLoader#2270] opened 2022-04-10 16:19 UTC
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

A number of dyes act strangely in tModLoader. Noteably, any dye using the following passes has strange artifacts when used: "ArmorHades", "ArmorGel", "ArmorLoki".

The affected dyes (and their shader pass names) are as follows:
* Grim Dye (ArmorHades)
* Bloodbath Dye (ArmorGel)
* Burning Hades Dye (ArmorHades)
* Hades Dye (ArmorHades)
* Gel Dye (ArmorGel)
* Skiphs' Blood (ArmorGel)
* Shadowflame Hades Dye (ArmorHades)
* Pink Gel Dye (ArmorGel)
* Loki's Dye (ArmorLoki)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8459376/client.txt)

### Steps to reproduce

1. Open any world with any character.
2. Equip any armor or any accessory with an EquipTexture.
3. Apply any of the listed dyes.

### Expected Behavior

The dye should affect the item the same as it does in vanilla _Terraria_.

### Actual Behavior

The dye has strange artifacts.

### Reproduction frequency

100%

### Additional Information

Attached are images of one example per shader pass side-by-side, with vanilla on the left and modded on the right.
![Hades Dye](https://user-images.githubusercontent.com/33076411/162628627-b6b810bf-3fe8-491b-a340-8637dbcab39d.png) Hades Dye (ArmorHades)
![Loki's Dye](https://user-images.githubusercontent.com/33076411/162628628-f36ee435-79d5-41cb-ae89-92b4ad117904.png) Loki's Dye (ArmorLoki)
![Pink Gel Dye](https://user-images.githubusercontent.com/33076411/162628629-850af22d-40b3-48b6-9db6-2f1a7989b8f8.png) Pink Gel Dye (ArmorGel)

Additionally, these artifacts get worse when the player moves.

Shader pass names are from `Terraria.Initializers.DyeInitializer.LoadArmorDyes()`.

**Comment by SolusIgnus** [comment] 2022-07-07 00:40
I am encountering the same issue, and this is on July 6th, 2022. Still not fixed yet, and it is currently TModLoader v2022.6.96.4 for Terraria 1.4.3.6

An issue like this, I would imagine, would be fixed right now, but a few updates later and a few months later, the same problem is here.

**Comment by domdsli** [comment] 2022-07-14 17:30
I see. It looks like this has been around for a few months now. What I can only do now is hope they'll address the issue and hopefully resolve it, eventually.

**Comment by JavidPack** [comment] 2022-09-29 17:51
I did some testing today, confirmed the issue on current tmod with direct3d and vulcan, and with older shader files and with linux shader files, and with terrarianetcore solution.

I still need to check older 1.4 tmod releases, see if this has always been an issue or if it is a recent thing

**Comment by Mirsario** [comment] 2022-09-30 14:22
It's really happening on ALL graphics APIs in TerrariaNetCore solution. Currently suspecting this to be an issue in MojoShader, which is apparently used without exceptions, unlike I previously thought. Can't imagine there being a C# FNA issue that would only affect something as little as this.
![image](https://user-images.githubusercontent.com/6795251/193290085-8cf00dd8-d9ed-4ee1-a839-896a231b951d.png)
![image](https://user-images.githubusercontent.com/6795251/193290092-ebae6785-b135-4d72-8886-a31708a5a129.png)
![image](https://user-images.githubusercontent.com/6795251/193290093-c9870bde-2256-47f0-95a1-8aca068868f5.png)


Player file for ease of checking: 
[bob2.zip](https://github.com/tModLoader/tModLoader/files/9685192/bob2.zip)

**Comment by Tyfyter** [comment] 2022-10-31 22:41
> I did some testing today, confirmed the issue on current tmod with direct3d and vulcan, and with older shader files and with linux shader files, and with terrarianetcore solution.
> 
> I still need to check older 1.4 tmod releases, see if this has always been an issue or if it is a recent thing

I'm fairly certain I noticed this issue on the first tML 1.4 version to be the main version, not sure if it occurred in older tML 1.4 versions

**Comment by Tyfyter** [comment] 2022-10-31 22:45
in addition, I'm fairly certain the cosine HLSL function was also broken at that time, and it may still be broken

**Comment by SoiBoySam** [comment] 2023-02-25 23:21
Made a whole account to see if there's been any updates on this? At least anything I can do on MY end that can fix this dumb thing? I checked myself on vanilla, the recent update and everything seems fine still.

**Comment by Mirsario** [comment] 2023-10-04 13:22
> Currently suspecting this to be an issue in MojoShader

Confirmed and fixed by Jopo & DominickKarma, [already merged into MojoShader](https://github.com/icculus/mojoshader/pulls?q=is%3Apr+acos+). We'll update the graphics natives on preview some time later this month, as they haven't yet been re-released officially in honor of this.

![image](https://github.com/tModLoader/tModLoader/assets/6795251/0f1c6703-6b6e-4817-ba12-608b2b81f3ad)

**Closed as completed** 2023-10-17 23:28 UTC
Labels: Bug, Needs Further Testing, Requestor-Player, Benefit - Medium, Complexity - Medium
