### ISSUE TITLE
Game crashes when audio device disconnects

### ISSUE THREAD

**Issue by NeuronExtractor** [bluemagic123/tModLoader#3738] opened 2023-08-19 16:09 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever my headphones disconnect, the game crashes. This has happened with both wireless and wired earbuds so this probably applies to all audio devices in general.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12386272/client.log)

### Steps to reproduce

1. Launch Tmodloader
2. Switch audio devices/disconnect headphones
3. Freeze for a few seconds
4. Crash :(

### Expected Behavior

the audio device should switch to whichever one you have selected because this is an issue with a lot of other games where audio just gets disabled whenever you try to switch audio devices and you have to restart for it to come back.

### Actual Behavior

the game freezes for a few seconds, then crashes

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment] 2023-08-29 17:33
Duplicate of #2863 and #2815, closing in favor of those.

**Closed as not planned by JavidPack** 2023-08-29 17:33 UTC
Labels: NEW ISSUE, Requestor-Player
