### ISSUE TITLE
Local (to vanilla) Resource Packs aren't loading

### ISSUE THREAD

**Issue by ThEnderYoshi** [bluemagic123/tModLoader#2662] opened 2022-07-01 18:08 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I have a resource pack saved at `Documents\My Games\Terraria\ResourcePacks`. It shows up in the Resource Pack browser, but clicking 'Back' with it enabled doesn't do anything. Enabling _only_ resourcepacks aquired from the Workshop is working properly.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9030856/client.log)

### Steps to reproduce

1. Place a valid Resource Pack on `Documents\My Games\Terraria\ResourcePacks`
2. Start tModLoader and go to the Resource Pack browser.
3. Enable the Resource Pack.
4. Click on the 'Back' button.

### Expected Behavior

The resource pack should load normally.

### Actual Behavior

Freezes for a few frames, then the browser reloads. Any loaded resource packs don't update.

### Reproduction frequency

100% of the time.

**Comment by Chicken-Bones** [comment] 2022-07-03 03:14
Duplicate of #1697

**Closed as completed by Chicken-Bones** 2022-07-03 03:14 UTC
Labels: Bug, Requestor-Player
