### ISSUE TITLE
ModConfig cause lambda can't fully unload

### ISSUE THREAD

**Issue by Solaestas** [bluemagic123/tModLoader#2503] opened 2022-06-05 13:26 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When I define a class inherited from ModConfig, every lambda expression in the mod can't be unloaded

### Log File

there is no log file

### Steps to reproduce

1. define a class inheried from ModConfig, public class TestConfig : ModConfig
2. define a lambda expression, var func = () => 114514;
3. reload the mod
![bug1](https://user-images.githubusercontent.com/49426220/172052573-b89431e3-ac92-4ee0-aefb-b674221aede8.png)

### Expected Behavior

The mod can't fully unload and the memory snapshot show there is a lambda expression
![bug2](https://user-images.githubusercontent.com/49426220/172052651-06c4047a-c293-4109-832c-c901a4ab300c.png)

### Actual Behavior

I don't know

### Reproduction frequency

always

**Comment by Chicken-Bones** [comment] 2022-06-07 21:54
Duplicate of #2137

**Closed as completed by Chicken-Bones** 2022-06-07 21:54 UTC
Labels: Bug, Requestor-Modders
