### ISSUE TITLE
Holding living leaf or wood wand makes wood rapidly drain from your inventory

### ISSUE THREAD

**Issue by AwhRyan** [bluemagic123/tModLoader#2239] opened 2022-04-02 01:57 UTC
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When holding the leaf wand or living wood wand, wood rapidly drains from your inventory at about 50 per second without placing anything

### Log File

https://user-images.githubusercontent.com/102840279/161361150-45fba1aa-5af2-45b9-b31b-5b3e15cb6a00.mp4

### Steps to reproduce

Add wood into your inventory
Hold the living wood or leaf wand

### Expected Behavior

It shouldnt use wood until you click while using it

### Actual Behavior

Taking wood rapidly and seemingly deleting it.

### Reproduction frequency

Every time i use these wands.

**Comment by Solxanich** [comment] 2022-04-02 14:14
Looks like a duplicate of #1863  
Will close if is the case.

**Closed as completed** 2022-04-30 16:31 UTC
Labels: Bug, Requestor-Player
