### ISSUE TITLE
tModLoader has the capability of making corrupted files in Windows.

### ISSUE THREAD

**Issue by TechnoMonkeyDJ** [bluemagic123/tModLoader#3221] opened 2023-01-28 13:10 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Windows has some names what should never be set. As in, player character names, player mod pack names or mod names restricted names for Windows, Example, naming your character. ........, r....., CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. And many, many more reserved names. tModLoader will make a corrupted file by letting you name them as those special reserved names. You seriously need to block special names from being set. I accidentally named a character ........ Had to use a shredder tool to remove it.

### Steps to reproduce

First step, name your character or mod pack ........ or r.....
Second step, realized as you goofed.
Third step, pull your hair out while you are trying to delete the file. 

### Expected Behavior

Makes corrupted files what are extremely hard to remove.

### Actual Behavior

Making a headache.

### Reproduction frequency

On windows every single time.

### Additional Information

Be silly and make a mod pack, a character, or mod in general, those special characters/names.

**Comment by TechnoMonkeyDJ** [comment] 2023-01-28 13:19
I personally have never named A character, world, mod pack. CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Before, and I'm not willing to find out what would happen. 
It's the folder itself It makes to be clear not Player.plr or World.wld they are fine and easy to delete. EG name your character .......
And play as it. It will make ........plr and undelatable file name ....... I found all the info from [https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file](url) For all the other unsafe names.

**Comment by TechnoMonkeyDJ** [comment] 2023-01-28 13:26
It's the folder itself It makes to be clear not Player.plr or World.wld they are fine and easy to delete. EG name your file. ........plr It makes it undelatable file name .......

**Comment by Exiled1** [comment] 2023-03-07 02:00
Oh! This looks like a good starting place to contribute! I'll be trying my hand at this if no one else is.

**Comment by Exiled1** [comment] 2023-03-07 03:21
Okay, so player names seem to not matter here, because of the check that's done in `GetPlayerPathFromName` in Main.cs.

However, I then named a map to `nul` and it gave me an error about failing to create the folder `C:\Users\Name\Documents\My Games\Terraria\tModLoader\Players\nul` But after checking it did actually go through and it created an illegal name.

Reproduction steps:
1) Create a player and world called nul, or some other reserved filename.
2) Attempt to play in the newly created map.
3) Terraria should crash and there will now be an illegal filename folder in the Players folder.

**Comment by Exiled1** [comment] 2023-03-07 03:25
It should be noted that you can delete the illegally named item very easily by using WSL to `rm -r [illegal file]`.

**Comment by TechnoMonkeyDJ** [comment] 2023-03-07 04:26
The issue would never occur if the player map data were named player_player or player_PMD e.g if the player name was NUL the map data would be named NUL_player or NUL_PMD then an illegal name would be impossible to be created. 
PMD would be Player Map Data.
But the special characters would have to be blocked outright \ / : * ? " < > | since you're not meant to use them at all.

**Comment by Exiled1** [comment] 2023-03-07 05:25
> The issue would never occur if the player map data were named player_player or player_PMD e.g if the player name was NUL the map data would be named NUL_player or NUL_PMD then an illegal name would be impossible to be created. PMD would be Player Map Data. But the special characters would have to be blocked outright \ / : * ? " < > | since you're not meant to use them at all.

So, I've been looking into this for about an hour and I figured it out. I'll just paste the exchange from the collaborators channel.

```
The behavior for actually saving the world under a filename happens under the Terraria.Utilities.FileUtilities Write function, it'll call TryCreatingDirectory in terraria utils and it doesn't seem to stop?

Then Terraria.Map.MapHelper.InternalSaveMap() also calls  TryCreatingDirectory with this path C:\Users\name\Documents\My Games\Terraria\tModLoader-dev\Players\nul

Whats weird is that when the TryCreatingDirectory function is called with that path it actually does throw an exception, but it's not because it tries to stop you from making that folder. Just because it cant find path '\\.\nul'.' as a path, HOWEVER, execution doesn't stop after that exception? Lmao

It goes RIGHT back to  TryCreatingDirectory with the nul folder path xD
[9:11 PM]
And the C# utils just... let it? Lmao

And there it is haha, the nul folders just chillin there
[9:13 PM]
Okay, I'll apply the fix, tbh I think throwing an exception is too much, adding a _ to it should suffice, since nul_ shouldn't have that behavior when used as a folder/file name
[9:15 PM]
Thats wild though, whatever error c# is throwing is completely unrelated to the actual use of a reserved keyword 
```
![image](https://user-images.githubusercontent.com/24551877/223327775-9b323f37-02ff-414e-9c0d-411699dcaca4.png)

So, after doing a bit of digging. I ended up naming my character `nul` and the world as `nul`. After triggering a world save (through dying, or simply save & exiting) Terraria just ends up not giving a crap and `Directory.CreateDirectory(folderPath)` just straight up works even if it *should* be an invalid name.

I'm working on a fix to this and getting it reviewed in a minute. That was an interesting hour ngl. Thanks C# stdlib I guess 🦀.

Oh, also regarding your question, yes, illegal characters are blocked because of `char[] invalidFileNameChars = Path.GetInvalidFileNameChars();` which will correctly block out those characters you just mentioned. Howeeeever, that doesn't include reserved filenames for some reason and there's also no function I saw that gets said reserved filenames.

**Comment by TechnoMonkeyDJ** [comment] 2023-03-07 05:34
Because they are technically not illegal names until the map data is created by playing the character because the map data doesn't exist until then. It's a catch-22. So to stop the catch-22, just putting anything on the end of the player map data will solve the problem I think.

**Comment by Exiled1** [comment] 2023-03-07 05:41
> Because they are technically not illegal names until the map data is created by playing the character because the map data doesn't exist until then. It's a catch-22. So to stop the catch-22, just putting anything on the end of the player map data will solve the problem I think.

![image](https://user-images.githubusercontent.com/24551877/223330705-b47a283c-c35f-4f1d-879d-bdb9a7546223.png)
That should solve that issue now lol. It really wasn't that many lines, I just had to make sure this wouldn't be an issue deeper in the codebase.

**Comment by TechnoMonkeyDJ** [comment] 2023-03-07 05:45
That would stop it, no more catch-22s would be created and most games, solve the issue by scrambling the name by setting it to numbers. But names are easier for save's troubleshooting reasons.

**Comment by Exiled1** [comment] 2023-03-07 23:05
Aight, done! :)

**Comment by Exiled1** [comment] 2023-03-08 08:59
Sweet, this issue can be closed now! @Chicken-Bones (sorry for the ping, idrk how the closing of issues works here haha)

**Closed as completed** 2023-03-08 09:13 UTC
Labels: Bug, Requestor-Player, Benefit - Medium, Complexity - Low
