### ISSUE TITLE
Main Menu theme resets when clicking on title

### ISSUE THREAD

**Issue by YokujinKaze** [bluemagic123/tModLoader#2794] opened 2022-08-02 14:07 UTC
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

TML v2022.6.96.4
Main Menu theme resets back to 1.3 theme when clicking on a specific area in the Main Menu after launching TML and finishsing the initial mod setup

https://gyazo.com/8fa5859103b33dddd3c95942f0ab4eeb

### Steps to reproduce

1 Start TML, wait until all mods are loaded
2 If you already have a modded Main Menu theme: click there the sun should be at noon
3 You seem to grab the sun in a non-vanilla theme and enables 1.3 theme

### Reproduction frequency

Always when first launching TML, doesnt happen if you reload mods

**Comment by direwolf420** [comment] 2022-08-02 14:48
Duplicate of #2719

**Comment by Chicken-Bones** [comment] 2022-08-03 20:08
Intended vanilla feature. Maybe we should provide a way for modded menu themes to prevent it?

**Closed as completed** 2022-08-03 20:08 UTC
Labels: Bug, Requestor-Player
