### ISSUE TITLE
IL Edits sometimes not applied on game launch

### ISSUE THREAD

**Issue by OblivionAXiS** [bluemagic123/tModLoader#4230] opened 2024-05-23 22:32 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Every once in a while when making IL edits for my mods, I run into some that will only apply when the mod is compiled or reloaded. If the game is opened with the mod already enabled, the IL edits are not applied. This bug is extremely inconsistent, as sometimes I have even seen the IL be properly applied for a minute or so in game and then be randomly reverted.
Written in the Additional Information section is one of the IL edits that I found reproduces this error for me, let me know if you want more and I can try to find some.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/15424518/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/15424519/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/15424520/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/15424521/Natives.log)

### Steps to reproduce

1. Load the IL edit listed in Additional Information in a mod (it can be an otherwise blank mod). I haven't found that it matters where you load it, whether in the Mod file or in a GlobalProjectile, GlobalNPC, or ModSystem, etc.
2. Close tModLoader
3. Open tModLoader again and fight the Lunatic Cultist. The IL edit should have made the big ice attack not split into fragments, but the gameplay says otherwise. Note: the bug is a bit inconsistent. Occasionally the IL edit will be properly applied, and will be reverted partway through the fight (like, by the 4th or 5th ice attack usually), or maybe never? (idk). Just close tModLoader and re-open it to try again.
4. If you quit the world and then Force Reload the mod (or Build and reload, or anything of the sort) and fight the Lunatic Cultist again, the change should now be properly applied. However, if you quit tModLoader and open it again, the same issue will occur.

### Expected Behavior

Obviously it seems pretty unusual to have to reload mods again after opening tmodloader before playing. This would be especially unintuitive for regular players, as its expected for the initial mod loading steps to properly handle applying mod changes to the game.

### Actual Behavior

The initial mod loading steps of tModLoader seem to not apply certain IL edits properly, such that they are reverted immediately after or very rarely partway through a gameplay session.

### Reproduction frequency

Very consistently with certain IL edits, though the actual results can vary slightly (i.e. sometimes taking an indeterminate amount of time before the IL edit is randomly reverted). Let me know if you want me to attempt to find more examples.

### Additional Information

```cs
using Terraria.ModLoader;
using MonoMod.Cil;
using Mono.Cecil.Cil;
using Terraria;

namespace TestMod
{
	public class TestMod : Mod
	{
        public override void Load()
        {
            IL_Projectile.VanillaAI += HookIceMist; // Ice mist attack lasts longer and should no longer shoot fragments
        }

        public static void HookIceMist(ILContext il)
        {
            ILCursor c = new ILCursor(il);

            // Ice Mist lasts longer
            if (!c.TryGotoNext(i => i.MatchLdcI4(464)))
            {
                return; // Patch unable to be applied
            }
            if (!c.TryGotoPrev(MoveType.After, i => i.MatchLdcR4(130)))
            {
                return; // Patch unable to be applied
            }
            c.Emit(OpCodes.Pop);
            c.Emit(OpCodes.Ldc_R4, 160f);
            if (!c.TryGotoNext(MoveType.After, i => i.MatchLdcR4(150)))
            {
                return; // Patch unable to be applied
            }
            c.Emit(OpCodes.Pop);
            c.Emit(OpCodes.Ldc_R4, 180f);

            // Ice Mist doesnt end up shooting (overexaggerated version of my normal change)
            if (!c.TryGotoNext(MoveType.After, i => i.MatchLdcR4(30)))
            {
                return; // Patch unable to be applied
            }
            c.Emit(OpCodes.Pop);
            c.Emit(OpCodes.Ldc_R4, 400f); // "Shoot every 400 frames"
        }
    }
}
```

**Comment by OblivionAXiS** [comment] 2024-05-23 22:36
Actually I guess this should probably be tagged as a modder issue because it affects my ability to program functional IL edits in my mod. I labeled it as a player issue because potential players would have no way of knowing about this issue and I'm pretty sure that the "Force Reload" button for mods isn't available for non-modders?
Is the tag able to be changed?

**Comment by Chicken-Bones** [comment] 2024-05-23 23:59
Do you think it could be related to #3878 ?
Can you try replacing the hook in the `IssueReproduction` mod in that ticket with your hook here?

**Comment by OblivionAXiS** [comment] 2024-05-24 01:48
It took me awhile to get an attempt that didn't have the hook removed from the moment I entered the world, but running garbage collection did seem to remove the hook during the fight. It's probably the same issue.
By the way, across the few times I ran into this issue, it most often seemed to crop up when attempting to modify the AI of projectiles or NPCs.

**Comment by Chicken-Bones** [comment] 2024-05-30 00:54
This will be the same issue, closing as duplicate of #3878

**Closed as not planned by Chicken-Bones** 2024-05-30 00:54 UTC
Labels: NEW ISSUE, Requestor-Player
