### ISSUE TITLE
Mod Packs - Created Mod Packs are instantly corrupted.

### ISSUE THREAD

**Issue by Volpiin** [bluemagic123/tModLoader#2791] opened 2022-08-01 14:48 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Users are unable to create a mod pack from Mod Packs menu in-game. They get instantly malformed and corrupted right after choosing a name for them.

Issue affects both simple players and modders who want to create modpacks.

![image](https://user-images.githubusercontent.com/65836194/182175656-d452f66d-74c8-4c73-bd8a-ce97c53fd23f.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9234814/client.log)

### Steps to reproduce

1a. Start tModLoader with some mods already subscribed from Workshop (skip subscribing if you already have some mods installed and enabled)
1b. After you reach main menu - enable all the mods (skip this step if you have them enabled already)
2. Enter Mod Packs tab in Workshop Hub
3. Press Save Enabled as New Mod Pack, name it however you want.
4. Notice that it will instantly return you to naming screen
5. Go back to Mod packs tab, notice that you'll see a prompt "The <name> modpack failed to be read properly, it might be malformed".

### Expected Behavior

Mod Pack file is created after inputting the name

### Actual Behavior

Mod Pack becomes malformed and corrupted right after choosing a name for it 

### Reproduction frequency

100%

### Additional Information

I'm somewhat suspecting file access issues, judging by the log file, but I'm not accustomed to how exceptions here look like.

**Comment by Chicken-Bones** [comment] 2022-08-01 20:24
Looks like a duplicate of #2661 which is fixed on preview (will be released to stable in a couple hours)

**Closed as completed by Chicken-Bones** 2022-08-01 20:24 UTC
Labels: Bug, Requestor-Modders
