### ISSUE TITLE
[1.4.4/Dev Build] Running the latest build doesn't work: immediately shows error

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3164] opened 2023-01-02 21:26 UTC
Note that this issue is similar to #3159 
### Version

Other (Latest 1.4.4-dev)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player (I had "Mod capability as a Modder" because I was going to talk about something else)

### Description

When launching tModLoader's 1.4.4 build, the main engine immediately crashes.
![image](https://user-images.githubusercontent.com/70764728/210277957-05b23a70-f156-4159-bdc2-720d7ec6f15f.png)
I followed the setup steps for contributing to tModLoader, pulled the latest changes, tried to open tModLoader, and it didn't work. I then regenerated the source, tried to open tModLoader again, and the problem is still there.
![image](https://user-images.githubusercontent.com/70764728/210278335-16930b78-4acc-4977-a4cf-d217f5b02606.png)
The last thing I did was delete everything from the tModLoaderDev folder and build the project, which creates the files there but even that didn't work. It still shows some files being dated 2022 November.

This thrown exception could be the reason why this is occuring: 
![image](https://user-images.githubusercontent.com/70764728/210279907-8328319c-eef7-4a65-af7d-1978faf90d16.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10333478/client.log)
Most recent [client.log](https://github.com/tModLoader/tModLoader/files/10333552/client.log)

### Steps to reproduce

1. Follow the dev setup steps and pull the latest commits from the 1.4.4 branch
2. build the project (For me, it said "Build Terraria")
3. Launch "Terraria" without debugging
![image](https://user-images.githubusercontent.com/70764728/210278582-4479758d-02f2-4435-a575-d1e0ec427b41.png)
4. The error should appear soon.

### Expected Behavior

tModLoader runs normally

### Actual Behavior

tModLoader doesn't run at all, just an error appears.
No splash screen, no game window, nothing.

### Reproduction frequency

100% of the time

### Additional Information

How do I really update the tModLoader-Dev folder in steamapps --> common?
I forgot how to do it, and I want to get the absolute latest version of tModLoaderDev branch build.

**Comment by direwolf420** [comment] 2023-01-02 22:08
Are both Terraria and tModLoader-Dev on the same drive?

**Comment by Setnour6** [comment] 2023-01-02 22:24
> Are both Terraria and tModLoader-Dev on the same drive?

Yes, both are on the C: Drive.
I recall that the dev build worked back in 2022 when I tested it.

**Comment by Solxanich** [comment] 2023-01-02 22:44
Some thoughts:
Typically Main.Asset errors come from issues with Terraria content files. Things like filename being upper or lower case.

 Try Verifying vanilla files?
Maybe also try running Terraria itself.

**Comment by Setnour6** [comment] 2023-01-02 22:55
> Some thoughts: Typically Main.Asset errors come from issues with Terraria content files. Things like filename being upper or lower case.
> 
> Try Verifying vanilla files? Maybe also try running Terraria itself.

I find it strange that the vanilla game could even cause errors like that.
I verified the integrity of the content files, started Terraria itself (it starts up well), and then the next thing I did was select the exe (Select Terraria), then clicked setup. I then ran Terraria with debugging via Visual Studio, but this time no exception message appeared, but the game still crashes right away with about the same error.
![image](https://user-images.githubusercontent.com/70764728/210283185-2853afc3-9d31-4b4c-a0ea-9c7c36d80a40.png)

Is there a step-by-step way that I should do that will allow me to launch the dev build with no early issues?

**Comment by Solxanich** [comment] 2023-01-02 23:16
With respect to vanilla, we reuse their audio, graphic assets from their install so that we don't duplicate files. And copyright reasons.
An unfortunate difference between Terraria and tmod is that tmod is case sensitive. 
If a file had case swapped during the 9+ updates for Terraria and steam didn't 'update' the file. Could be whats going on here.

Everything checks out with what you did, which leaves this as strange to me. 
A final idea is to delete the content folder in tmodloader and content folder in Terraria folder, per above. And thats all I got at the moment, unfortunately

**Comment by Setnour6** [comment] 2023-01-02 23:41
> With respect to vanilla, we reuse their audio, graphic assets from their install so that we don't duplicate files. And copyright reasons. An unfortunate difference between Terraria and tmod is that tmod is case sensitive. If a file had case swapped during the 9+ updates for Terraria and steam didn't 'update' the file. Could be whats going on here.
> 
> Everything checks out with what you did, which leaves this as strange to me. A final idea is to delete the content folder in tmodloader and content folder in Terraria folder, per above. And thats all I got at the moment, unfortunately

That is strange indeed. Is it possible for tModLoader to not be case-sensitive?
I followed the final idea and the error unfortunately still appears. This was tested on a branch I was working on for secret seed additions (#3165), and Main itself was not changed at all.
![image](https://user-images.githubusercontent.com/70764728/210285120-45580350-3a65-44eb-af52-d28f1a68ba87.png)
I'm hoping that this can be looked at more and looked into further to resolve the issue so playtesting the dev build can be possible.
Also, did the error also appear for you?

**Comment by Chicken-Bones** [comment] 2023-01-03 00:51
Please DM me on Discord and I will assist you

**Comment by Setnour6** [comment] 2023-01-03 01:01
> Please DM me on Discord and I will assist you

I still don't use discord, but I can message you via email (and try to add you as a contact there)

**Comment by Chicken-Bones** [comment] 2023-01-03 01:53
Should be a duplicate of #3159 and fixed by the same d1249475b7adfb2f8d259fe35cafd8bf362de60b

**Closed as completed by Chicken-Bones** 2023-01-03 01:53 UTC
Labels: Requestor-Modders, NEW ISSUE
