### ISSUE TITLE
Game crash when unplug earphones

### ISSUE THREAD

**Issue by EdrowsLuo** [bluemagic123/tModLoader#3978] opened 2023-12-11 02:00 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The game will crash if you unplug your earphones.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13630117/client.log)

### Steps to reproduce

1. Launch tml when you have your earphones plugged.
2. Unplug your earphones from your computer
3. Game crash

### Reproduction frequency

100%

**Comment by Destructor-Ben** [comment] 2023-12-13 21:08
Likely related to the FAudio mess, this has occurred to me before but I don't think its happened with the current dll and version.

**Comment by JavidPack** [comment] 2024-01-09 00:04
Duplicate of #2863, we will continue tracking the issue there.

**Closed as not planned by JavidPack** 2024-01-09 00:04 UTC
Labels: NEW ISSUE, Requestor-Player
