### ISSUE TITLE
Deleting all characters bug.

### ISSUE THREAD

**Issue by BialyEnderman** [bluemagic123/tModLoader#2104] opened 2022-01-20 17:06 UTC
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When you create an character named "." and then delete it, it clears whole players folder, deleting all characters.

### Steps to reproduce

1. Create character named "."
2. Delete this character

### Expected Behavior

It should only delete character you choose to delete.

### Actual Behavior

It deletes all characters.

### Reproduction frequency

100% of times.

**Comment by steviegt6** [comment] 2022-01-20 18:34
Technically a duplicate of #456. ~~despite it being closed. Looks like Yorai never got around to fixing this?~~

**Comment by Solxanich** [comment] 2022-01-20 19:12
This was fixed in 1.4.
1.3 still has this bug.

As 1.3 won't be updated, the former issue was closable.
To make bug go away, play the 1.4 alpha per discord instructions

**Comment by JavidPack** [comment] 2022-09-13 19:23
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.

**Closed as completed by JavidPack** 2022-09-13 19:23 UTC
Labels: Bug, Bug - Vanilla, Requestor-Player
