### ISSUE TITLE
Unknown crash that seems to be permanent

### ISSUE THREAD

**Issue by KibyA** [bluemagic123/tModLoader#3141] opened 2022-12-16 05:15 UTC
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I literally just got on my pc, tried to boot up TModloader and was showing me the same error text over and over again, uninstalled and reinstalled, trashed and redownloaded it, and updated my pc to no avail

### Log File

System.Exception: Multiple extensions for asset Music\Music_19, (.ogg, .mp3)
   at ReLogic.Content.Sources.ContentSource.SetAssetNames(IEnumerable`1 paths) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\Sources\ContentSource.cs:line 28
   at ReLogic.Content.Sources.FileSystemContentSource..ctor(String basePath) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\Sources\FileSystemContentSource.cs:line 20
   at Terraria.IO.ResourcePack.GetContentSource() in tModLoader\Terraria\IO\ResourcePack.cs:line 97
   at Terraria.GameContent.AssetSourceController.<>c.<UseResourcePacks>b__13_2(ResourcePack pack) in tModLoader\Terraria\GameContent\AssetSourceController.cs:line 51
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Terraria.GameContent.AssetSourceController.UseResourcePacks(ResourcePackList resourcePacks) in tModLoader\Terraria\GameContent\AssetSourceController.cs:line 49
   at Terraria.Main.LoadContent() in tModLoader\Terraria\Main.cs:line 8655
   at Terraria.Main.Initialize() in tModLoader\Terraria\Main.cs:line 5202
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 779
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 411
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231

### Steps to reproduce

1. Clicked on the "play" button on the TModloader 
2. wait for it to load
3. got the error text

### Expected Behavior

Suppose to load and run TModloader

### Actual Behavior

A constant crash text repeating over and over again

### Reproduction frequency

100%

**Comment by direwolf420** [comment] 2022-12-19 10:11
Duplicate of #3140

**Closed as not planned** 2023-01-02 16:44 UTC
Labels: NEW ISSUE, Requestor-Player
