### ISSUE TITLE
Server crash in Linux ARM

### ISSUE THREAD

**Issue by SudoJanast** [bluemagic123/tModLoader#2713] opened 2022-07-13 19:48 UTC
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Launched Using Local Dotnet
Unable to load one or more of the requested types.
Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
 (see server.log for full trace)
Server crash: 7/13/2022 7:46:42 PM
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Terraria.ModLoader.LoaderManager.AutoLoad() in tModLoader\Terraria\ModLoader\Loader.cs:line 79
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 92
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 225
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'

Please check server.log to determine if a mod is responsible, otherwise head to #support in the tModLoader Discord

### Steps to reproduce

Just start the script server

**Comment by nullapple** [comment] 2022-08-09 21:06
Assuming that you're on the latest tModLoader v2022.7.58.8 [this is a bug that the devs are working on](https://github.com/tModLoader/tModLoader/pull/2639). I've made a fix for it [here](https://github.com/NicolaeBet/tModLoader-ARM64-Fix/releases/tag/v2022.7.58.8). Just replace the dll files with the dll files from the zip. Chmod the start-tModLoaderServer.sh and run it as sudo and it should work.

**Comment by SudoJanast** [comment] 2022-08-14 14:48
Yes, but the mod browser doesn't work

**Comment by nullapple** [comment] 2022-08-14 15:39
> Yes, but the mod browser doesn't work

Yes, I think this is because steamworks.dll doesn't work with linux. Just migrate your mods from windows then. Make a modpack in tmodloader in windows and copy the mods over to the linux machine. Specify the mod path in the serverconfig.txt and place the mods (including the enabled.json) into the modpath folder.

**Comment by SudoJanast** [comment] 2022-08-14 15:49
This is the real problem, all the mods installed via workshop are not in the mods folder

**Comment by Chicken-Bones** [comment] 2022-08-15 18:12
Duplicate of #2639

**Closed as completed by Chicken-Bones** 2022-08-15 18:12 UTC
Labels: Bug, Requestor-Modders
