### ISSUE TITLE
Can't open tModLoader on Mac (M1)

### ISSUE THREAD

**Issue by NickVolynkin** [bluemagic123/tModLoader#2145] opened 2022-02-12 11:57 UTC
### Version

Latest public-1.4-alpha

### OS

Mac (11.5.2 on M1)

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

Freshly downloaded tModLoader ([v0.11.8.6](https://github.com/tModLoader/tModLoader/releases/tag/v0.11.8.6)) won't open on macOS Big Sur 11.5.2 (M1)

```console
$ nick@Nicks-Mac-mini /Applications % open tModLoader.app 
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2561, NSUnderlyingError=0x12a80eae0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x12a808d50 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}
```

Seems to be some Apple-side issue, similar error mentioned in https://developer.apple.com/forums/thread/686838.

---

Problem resolved with

```bash
chmod -R 755 /Applications/tModLoader.app
```

which is definitely an overkill, since not all files need have to be `755`. But apparently, there's a certain file somewhere in the application directory which lacks the execution permission.

---

I'll research more and post updates.

**Comment by Solxanich** [comment] 2022-02-12 17:23
Hello,

Please use the discord for requesting help on getting tModLoader to launch before coming to github for help.
We don't look at the github often, and 99% of the time, we won't provide support here.

I will do a favor here and indicate that 
a) M1 is very poorly supported on v0.11.8.6 and earlier due to 1.3 just not having the back-end needed to make it work fully. 
b) 1.4 alpha is only versions 0.12 and greater. You did not run the Alpha, and you should seek support in the discord to address what you might have done wrong if your intent is to run the Alpha

Further still, M1 requires above and beyond permissions when downloading from an internet source (ie outside of Steam). The resolution method you described is fully expected and not a bug.

Closing in light of that this is expected behaviour on M1 for 1.3 manual downloads.

**Closed as completed by Solxanich** 2022-02-12 17:23 UTC
Labels: Requestor-Player
