### ISSUE TITLE
Bug: Funky character movement in Linux version

### ISSUE THREAD

**Issue by ImP-Gamer** [bluemagic123/tModLoader#2463] opened 2022-06-01 02:52 UTC
### Version

Latest Official (1.3)

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When running using sprint boots and then changing direction character becomes unresponsive and input is sent without pressing keys.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8810643/client.log)

### Steps to reproduce

1. Equip any speed buff
2. Run in one direction straight
3. Change directions

### Expected Behavior

The character should not become unresponsive to inputs and inputs should not be sent if I'm not pressing anything.

### Actual Behavior

The character movement becomes funky and opening a text box (Recipe Finder mod) reveals input is sent with delay.

### Reproduction frequency

Not very reliable but running in the same direction in a straight line and then changing directions almost always works.

### Additional Information

This bug has been reported before [here](https://steamcommunity.com/app/105600/discussions/0/1319961618835795122/). It was fixed in the unmodded Terraria but not in tModLoader.

This is not a hardware issue, I have tested this alongside a text editor and the editor works fine.
Additionally, even if I turn off sticky keys in the Ubuntu settings, opening the game turns them on.

**Comment by direwolf420** [comment] 2022-06-01 07:33
Duplicate of #632
Fix found here

**Comment by JavidPack** [comment] 2022-09-13 23:22
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.

**Closed as not planned by JavidPack** 2022-09-13 23:22 UTC
Labels: Bug, Requestor-Player
