### ISSUE TITLE
Game crashes midway through the game, and restarting doesn’t fix it.

### ISSUE THREAD

**Issue by ikun568** [bluemagic123/tModLoader#4154] opened 2024-04-09 04:43 UTC
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

(Machine-translated from Chinese)
When I entered a mine, the screen suddenly got stuck and the game crashed.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14913527/client.log)

**Comment by Mirsario** [comment] 2024-04-09 14:06
Duplicate of #4144.
I've now renamed the above issue to be searchable. Subscribe to it to keep track of the issue.

**Closed as not planned by Mirsario** 2024-04-09 14:06 UTC
Labels: Requestor-Modders, NEW ISSUE
