### ISSUE TITLE
[1.4] High DPI scaling issues

### ISSUE THREAD

**Issue by Swordling1** [bluemagic123/tModLoader#2194] opened 2022-03-12 02:11 UTC
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

On High DPI Monitors with scaling over 100% (250% on a 3840 x 2160 laptop screen in my case) terraria will behave weirdly, no other way to put it. The startup screen will take up 1/4 of the screen size, gameplay will look extremely blurry, both steam and discord overlays will not behave correctly, windowed will be bigger than the monitor and almost impossible to reverse or move, and it will randomly set the screen resolution to the lowest possible setting or set it to windowed.

this does not happen when the scaling in windows settings is set to 100%, in the vanilla game, or stable.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8236820/client.log)

### Steps to reproduce

1. set scaling above 100% in windows settings on a high dpi monitor
2. in the settings in terraria set the resolution to your screen size

**Comment by Swordling1** [comment] 2022-03-12 02:13
I can't use 100% scaling in windows frequently because text outside of games are unreadable
I'm sorry I should've put this in additional information

**Comment by Solxanich** [comment] 2022-04-17 19:48
Duplicate of #2078 . 
Closing as a duplicate.

**Closed as completed by Solxanich** 2022-04-17 19:48 UTC
Labels: Bug, Requestor-Player
